### ISSUE TITLE
this project is amazing

### ISSUE THREAD

**Issue by sil2** [fsantini/KoboCloud#10]
No issues, just to say THANK YOU! 
your tool is so great!
One thing I still missing - "share notes" 
if one day you will find a solution to sync highlights to facebook or Instagram somehow -  will be nothing to dream about

**Comment by fsantini** [comment]
Thank you very much for your appreciation! What do you mean by "share notes"? Re-uploading the notes you take on one device to the cloud?

**Comment by sil2** [comment]
I used to use kindle for years and missing very helpfull feature - share highlights.
Share some paragraphs on twitter.  Kindle has this twitter integration (over Evernote I think)
Koreader has Evernote but there is no way to highlight and share a particular highlight but only sync all highlights at the time with Evernote.

**Comment by fsantini** [comment]
Ah I understand. This is definitely above my paygrade then, sorry :)

**Comment by sil2** [comment]
I know, I know.  I was thinking to do it on my own, 
Some kind of small service to post on twitter from sqlLiteDB
All notes and highlights are stored in kobo sqlLiteDB file. 
On press sync books - send this file to a server, and process there and tween last records automatically..... or on closed temp Telegram channel. and then, from there share whatever needed...

**Comment by sil2** [comment]
Maybe you can advise me how to handle book sync press on kobo?

**Comment by fsantini** [comment]
The way I do it (and I've seen many other scripts do the same) is to check for WiFi to become available, This is done by adding a udev rule that calls a script (see [this file](src/etc/udev/rules.d/97-kobocloud.rules)). From there, you can use curl to send the file to the server you want.

**Comment by sil2** [comment]
thanks a lot.

**Comment by sil2** [comment]
sorry.... very last question - 
how you test your script?
Every time compile, send to an e-reader and restart?

**Comment by fsantini** [comment]
No I test it on my Linux PC. Out of laziness, the configuration for the PC is also included in this repository. Look for [config.sh](src/usr/local/kobocloud/config.sh) and you will see that it checks if the architecture is x86 and in this case it calls the config_pc.sh script.

**Comment by sil2** [comment]
Oh, ok... I see. I'm on Linux too. should be easy
Thanks a lot again.
