### ISSUE TITLE
pCloud and invalid link code

### ISSUE THREAD

**Issue by giorgina51** [fsantini/KoboCloud#101]
Hello and a happy new year!

I installed Kobocloud in my Kobo Libra H20, my files are on pCloud website in a folder named "ebooks" but there is not sync.

get.log tells me  :

> `Status: 3
> Output: 
> * Rebuilt URL to: https:// "result": 7001 "result": 7001/
> * Port number ended with ' '
> * Closing connection -1
> * Rebuilt URL to: https:// "result": 7001 "error": "Invalid link 'code'." /
> * Port number ended with ' '
> * Closing connection -1
> * Rebuilt URL to: https:// "error": "Invalid link 'code'."  "result": 7001/
> * Port number ended with ' '
> * Closing connection -1
> * Rebuilt URL to: https:// "error": "Invalid link 'code'."  "error": "Invalid link 'code'." /
> * Port number ended with ' '
> * Closing connection -1`

Here is my link : _https://e1.pcloud.link/publink/show?code=...._

It's not starting with https://my.pcloud.com/ or https://u.pcloud.link/ so I suppose it's the problem.

Can you help me please?

**Comment by fsantini** [comment]
Hi Giorgina!

The script should work with any prefix. Would you mind sending me your code via email, so I can test? I promise it'll only be for debugging purposes! francesco.santini@gmail.com

Cheers,

Francesco

**Comment by fsantini** [comment]
The problem was the US and EU pCloud APIs have different addresses.
6e72d2c should fix this.

**Comment by giorgina51** [comment]
Thank you, it seems to work :)

But now I've got trouble to download my ebooks: 
since yesterday, only 168 on 542 were transferred in my kobo. When I synchronize, it's finished in 5 seconds and nothing seems to be happening.
Only when I connect it to the computer then disconnect it, some books are then transferred.

Can you help me one more time please?

**Comment by fsantini** [comment]
The synchronization button does not reflect the status of Kobocloud. There is unfortunately currently no way to give feedback on the progress of the download. I think that the scripts are working fine, but they just need quite a long time to download all these books. And my experience is that the download is quite slow.

Try leaving your Kobo on for an hour or so and at some point it should finish.

**Comment by giorgina51** [comment]
Hello again Francesco.
It's on since monday, no more books are synchronized.
