### ISSUE TITLE
Does sync mean two-way-sync?

### ISSUE THREAD

**Issue by ct2034** [fsantini/KoboCloud#102]
The description says, this syncs files to cloud services. But from reading the code, it only seems to download them. Am I missing something?

**Comment by fsantini** [comment]
Hi Christian see #100

**Comment by ct2034** [comment]
Hi fsantini.
I think #100 deletes files from the device when they are no longer in the cloud.
What I am asking for is uploading files that are created or changed on the device to the cloud.

This is not possible, right? Because then I think the term `sync` is a little misleading. It is more of a download. ;-)

**Comment by fsantini** [comment]
Ah yes you are right. There is no upload. It's a one-way sync ;) 
Upload could potentially be implemented with rclone (see #35 ) but we didn't end up going that way, because it would mean fundamentally changing how the scripts currently operate.

**Comment by ct2034** [comment]
Oh nice, rclone seems very powerful. I will look into that

**Comment by ScottESanDiego** [comment]
If you have any good ideas on how to make the `rclone` stuff better, please make PR (or even just a comment) @ct2034 .  I have on to-do list so far:

1. Make the rclone binary download happen at install time (vs bundling it) from the fixed rclone URL
2. Update the ARM rclone binary (taken care of by (1) really)
3. Put each cloned "thing" into a subdirectory (so you can reasonably have >1 `RCLONE foo` line)

If you wanted to add to that list (like, figure out a sane 2-way sync), or implement any of those, it'd be appreciated!

**Comment by krillin666** [comment]
This feature would be greatly appreciated for annotating PDF documents. With Zotero you can use Zotfile to send a specific PDF to a folder, this folder is synchronized with nextcloud and appears on my Kobo thanks to this plugin.
Unfortunately, all the highlights I make on the KoReader app are not synced back to Zotero because I realised that the sync is only one way :confused:
