### ISSUE TITLE
[suggestion] Mention that Safari automatically unpacks the release tgz in the installation docs

### ISSUE THREAD

**Issue by VanTudor** [fsantini/KoboCloud#103]
I suggest mentioning in the installation docs that Safari defaults to unpacking tgz files (for people that use Macs). I spent half an hour trying to figure out why the .add folder wasn't showing up up 😁 Kinda silly/should've known, but y'know, might help other people.

For others bumping into this: make sure you copy a .tgz file and not a .tar and just use Chrome to download the release.

**Comment by fsantini** [comment]
Good point. I'll modify the readme!

**Comment by fsantini** [comment]
Fixed by 5f52738, Thanks!
