### ISSUE TITLE
HTML files won't download from google drive

### ISSUE THREAD

**Issue by techCarpenter** [fsantini/KoboCloud#104]
I want to be able to upload `.html` files to my google drive folder and then have them appear on my Kobo along with ebooks.

Right now, I can't get `.html` files to download from gdrive so I have to manually upload them via USB.

Is there something I've done wrong or can this functionality be added?

Looking forward to hearing your thoughts.

**Comment by fsantini** [comment]
Hi! I had a look at the code and it seems that html files should be downloaded too. Do you see the html files in your `get.log` file after a synchronization?

**Comment by VPeeters** [comment]
I'm not sure of this, but I believe KoboCloud doesn't care about file extensions (except for kepub). Are you certain they are not downloaded? Please upload the logs after reboot with a html file in your GDrive.

**Comment by techCarpenter** [comment]
@fsantini Okay! I don't see the `html` files in the log... just the 3 ebooks in the folder.

@VPeeters I figured that would be the case, but I don't see the `html` files in the `Library` folder. I have two `html` files in the GDrive folder and I've rebooted a few times with `kobocloudrc` changes after a `html` file was in the folder on GDrive.

[Here's a copy of the `get.log`](https://github.com/fsantini/KoboCloud/files/7919571/get.log)

**Comment by fsantini** [comment]
I think I found the problem: it's in lines 20 and 25 of `getGDriveFiles.sh`:
```
   entryName=`echo $entry | sed -n 's/\\\x5b\\\x22.*,\\\x22\(.*\)\\\x22,\\\x22application.*$/\1/p'`
```
That `application` refers to the filetype `application/epub+zip` which is the epub MIME format. To support html we should look for `text/html`... But on the other hand, it would be better to have a more general regular expression.

If I have some time to play with it I'll have a look.

**Comment by techCarpenter** [comment]
Terrific! Thanks for looking into this. I appreciate it.
