### ISSUE TITLE
Workaround for the JAN-2022 firmware problems

### ISSUE THREAD

**Issue by caasols** [fsantini/KoboCloud#107]
Not necessarily an issue, but the workarounds I found for the problems that came up with the new firmware.

The firmware released by Kobo/Rakuten on JAN-2022 will basically wipe out your machine entirely. This means that the Kobo Cloud mod will disappear, together with all the books.

You will find some trouble trying to force the Kobo to (re)install the mod after, since it seems to have changed the structure of the folders of the device. Don't feel alarmed. 

These are the workaround steps that I discovered that seemed to have work for me:
(1) Disconnect and reconnect your device to the computer. It seems that doing this forces the Kobo to create the old folder structure

(2) On the .kobo folder, check if there is another firmware there. You have two options here, but I'd try the first option first:
delete the file that exist there, and put the modded one + forcing a shutting down + turning your device on
replacing your modded firmware for the one inside Kobo using the same file name (e.g., KoboRoot 12.4.44.1.tgz)

(3) Repeat your previous configurations in the kobocloudrc file, and it should be working! :)

Troubleshoot information:
Kobo Libra H2O (2021 with micro usb)
Firmware 4.31.19086 (2adb3f45ad, 1/20/22)
Mac M1 + Mac Monterey 12.1

**Comment by fsantini** [comment]
Thanks, good to know!

**Comment by Grundle** [comment]
I cannot get this thing to work anymore. Tried to reinstall this 3x & it no longer syncs

**Comment by groentebroer** [comment]
> I cannot get this thing to work anymore. Tried to reinstall this 3x & it no longer syncs

@Grundle 
Please create a new issue for this. Specify more information, Firmware version, etc.
If you are talking about Dropbox, this could be the case, they changed their whole API setup.
