### ISSUE TITLE
Support for iCloud Drive

### ISSUE THREAD

**Issue by holeyman** [fsantini/KoboCloud#108]
Considering the number of Apple users, this would be great.

**Comment by fsantini** [comment]
Hi, sure, but I don't have a Mac and I don't know how iCloud works. Are public links possible as with the other services? Would you be willing to provide such a link so we can try and develop the appropriate procedure?

**Comment by JaymesRS** [comment]
Hey, I am a pretty comfortable Mac user and am happy to help provide help if I can too.

**Comment by lorenzolewis** [comment]
Just tried this out and no longer working. Apple has restricted iCloud sharing behind an authentication wall now: https://apple.stackexchange.com/questions/389756/sharing-folders-on-icloud-with-non-icloud-users-catalina
