### ISSUE TITLE
Warranty

### ISSUE THREAD

**Issue by dfranklinstein** [fsantini/KoboCloud#109]
If I install this mod, will my warranty on my Libra 2 be deemed redundant? I know if it did, its not the fault of the creators, I'm just wanting to know before installing. Im UK btw.

**Comment by tylpk1216** [comment]
If you uninstall KoboCloud without any problems, the relevant KoboCloud files installed on the device are removed. I think Kobo does not know about it.

**Comment by fsantini** [comment]
It's a tricky question, officially we cannot take any responsibility. However, as @tylpk1216 said, if you have any problem, uninstalling the mod shouldn't leave any trace, and Kobo should not complain. Worst case scenario, you can always reflash the original firmware.
