### ISSUE TITLE
Latest firmware issue?

### ISSUE THREAD

**Issue by louloubelle75** [fsantini/KoboCloud#110]
Should the .tgz file stay in the .kobo directory? It keeps disappearing after I have copied it in.

**Comment by mswitakowski** [comment]
I believe that it is expected to disappear. The contents are unpacked to the root directory of Kobo on installation.

**Comment by louloubelle75** [comment]
Thanks for your reply. The sync stopped working so I set it up again.
Got it working and books loaded once. Now it is not working. I hadn't
loaded any books that way recently so not sure exactly when it stopped
working. I have tried setting it up again a few times - no luck. Also I
tried to follow directions by other user that suggests naming of .tgz file
but unsure what they mean.

**Comment by caasols** [comment]
Hello,

Have you tried this: https://github.com/fsantini/KoboCloud/issues/107 ?

**Comment by louloubelle75** [comment]
Hi

Yes I have tried to follow your workaround. There isn't a .tgz file in .kobo to rename on my Libra 2.

**Comment by Jolopu** [comment]
Same problem here with my new Libra 2. Im on FW 4.31.19086 which is the latest as of March 4th 2022. After copying the KoboRoot.tgz file into .kobo and restart I see an update in progress message. After plugging into my Mac Monterey and checking the .kobo folder, the KoboRoot.tgz file is gone but no kobocloud folder has been created. Stuck there.

**Comment by caasols** [comment]
Im unsure if this hack is fully compatible with the Libra 2. Have you tried following the steps I posted on a similar thread?

**Comment by Jolopu** [comment]
I read your hack but there is no firmware file in the .kobo folder. And where would I get the modded firmware you suggested?

**Comment by caasols** [comment]
If there is no firmware in the folder, just add the one from Kobocloud and reset the machine.
There is no modded firmware. It's the one from Kobocloud available in this repo.

**Comment by Jolopu** [comment]
That's what I did as I described above. After resetting the machine there is no kobocloud folder in .kobo and the KoboRoot.tgz is gone.

**Comment by caasols** [comment]
Then I suspect that Kobocloud is not compatible with the Libra 2 recent changes. Sorry I couldn't help further.
