### ISSUE TITLE
Sync with Google drive invokes curl too many times

### ISSUE THREAD

**Issue by mswitakowski** [fsantini/KoboCloud#111]
I noticed that synchronization with google drive invokes curl multiple times (about 5) even when only 1 file is downloaded. I debugged the issue and found that there a few additional echo invocations in the find_files() function. They look like a leftover from debugging. See https://github.com/fsantini/KoboCloud/blob/ebfd5c2b0ab1163fdaf5e835e42049ccf50070e5/src/usr/local/kobocloud/getGDriveFiles.sh#L17 
The list returned by find_files() is too long and contains many broken entries. Only echo "$2$entryName|$entryCode" should be there.

I modified the script locally on my Kobo and confirmed that it addresses the issue.

**Comment by fsantini** [comment]
Thanks! Fixed!
