### ISSUE TITLE
Google drive does not work with curl's "-C -" parameter

### ISSUE THREAD

**Issue by mswitakowski** [fsantini/KoboCloud#112]
When curl is invoked for files that already exist on the Kobo the following error is returned:

{ [5 bytes data]
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
{ [1 bytes data]
* HTTP server doesn't seem to support byte ranges. Cannot resume.
* Connection #0 to host drive.google.com left intact
Remote file information:
  Status code: 500
Error: Server error

Removing the "-C -" parameter addresses the problem, but then existing files are always re-downloaded, which is slow and not scalable.

The error will stop the whole sync process from continuing. It seems that the synchronization generally works, because the newest files are returned first on the list. Otherwise, downloading new files would never start if an attempt to sync an existing file fails earlier. It stops the loop iterating over the files. Maybe a different approach is going to be needed for google drive. For example, files could be checked for existence before invoking curl.

**Comment by fsantini** [comment]
Hi, thanks. Yes I can confirm that it's a problem. Working on it.

**Comment by rlyons20** [comment]
it seems to not like certain files, in particular...
