### ISSUE TITLE
KoboCloud slows down my Kobo Libra 2

### ISSUE THREAD

**Issue by mswitakowski** [fsantini/KoboCloud#113]
I can consistently reproduce slowness of Kobo Libra 2 when KoboCloud is installed. The slowness can be easily observed in those two scenarios:
- While inside a book, press the power button to put the device to sleep. With KoboCloud it takes about 2-3 seconds for the book cover to appear. Without KoboCloud it is almost instantaneous. 
- While inside a book, open the top menu and press "back" to go to the main screen. Again with KoboCloud installed it takes about 2 seconds longer.

Some observations:
- It happens even if the config file does not specify any cloud directory to sync with.
- It continues after the extra mountpoint created by KoboCloud is unmounted (through telnet while the device is running)
- Removing the eth* line from udev rules does not help

I also looked at CPU utilization with top during the above mentioned slow operations. I couldn't notice any difference between KoboCloud installed and uninstalled. I compared the list of running processes with ps aux and didn't find any difference.

The issue was also mentioned here: https://www.mobileread.com/forums/showthread.php?t=332254&page=17

**Comment by groentebroer** [comment]
@mswitakowski If you disable WiFi, no sync will be done and KoboCloud will not slow don the e-reader.
