### ISSUE TITLE
helping With Installing Pt2

### ISSUE THREAD

**Issue by dfranklinstein** [fsantini/KoboCloud#118]
Mac, Libra 2
Questions still apply - what happens if I install it into a folder within a folder?

_Originally posted by @dfranklinstein in https://github.com/fsantini/KoboCloud/issues/117#issuecomment-1047291960_

Accidentally closed the issue; I'm also new to Github lol - thought it meant close as in close the tab.

I realised after talking it over with some more knowledgeable friends, that the real issue is I'm really struggling with installing: I can't get the google drive link in the config (can't edit it, its in terminal), and I tried to put it in the "get.log" but that didn't do anything. What do I do?

**Comment by fsantini** [comment]
Hi, first of all, don't panic! You haven't broken anything. What did you do exactly? Have you copied the KoboRoot.tgz in the .kobo folder and rebooted?

**Comment by dfranklinstein** [comment]
Thank you for replying!

I’m not sure; I don’t know is I put the KoboRoot.tgz in the .kobo folder and rebooted or put it within the Kobo folder within the .kobo folder and rebooted 

Considering the correct files are in .add, I’m going to assume the former.

What should I do to properly install by adding the link to the correct file (the one that will only open within terminal so I can’t edit)?

**Comment by fsantini** [comment]
Ok that looks good. You need to edit the kobocloudrc file. From what I understand, if you click on it, a terminal opens? I don't know Mac, but there must be an option to choose what program you want to open the file with, See here: https://www.bleepingcomputer.com/tutorials/open-file-with-different-program-on-mac/

Select TextEdit and you should be able to edit the file correctly.

**Comment by dfranklinstein** [comment]
Thanks! I managed to open the file in text edit, but it won't let me save it because it is locked?
