### ISSUE TITLE
Pinging 'dropbox.com' not possible in some regions

### ISSUE THREAD

**Issue by yu-kari** [fsantini/KoboCloud#12]
in `get.sh`, line 14 to 27 :

````bash
#check internet connection
echo "`$Dt` waiting for internet connection"
r=1;i=0
while [ $r != 0 ]; do
  if [ $i -gt 60 ]; then
    ping -c 1 -w 3 dropbox.com
    echo "`$Dt` error! no connection detected" 
    exit 1
  fi
  ping -c 1 -w 3 dropbox.com >/dev/null 2>&1
  r=$?
  if [ $r != 0 ]; then sleep 1; fi
  i=$(($i + 1))
done
````
Dropbox is pinged to check whether internet connection is available. But due to some reasons, Dropbox is not reachable in China, thus pinging will never be succeed. Ping `www.microsoft.com` or `aws.amazon.com` may be a better choice.

**Comment by fsantini** [comment]
Thanks! Fixed in Master.
