### ISSUE TITLE
No kobocloud folder on Libra 2 with FW 4.31.19086

### ISSUE THREAD

**Issue by Jolopu** [fsantini/KoboCloud#125]
Im on FW 4.31.19086 which is the latest as of March 4th 2022. After copying the KoboRoot.tgz file into .kobo and restart I see an update in progress message. After plugging into my Mac Monterey and checking the .kobo folder, the KoboRoot.tgz file is gone but no kobocloud folder has been created. Stuck there.

**Comment by jucor** [comment]
The kobocloud folder should be in `ROOT_OF_YOUR_KOK/.add/kobocloud/` .
