### ISSUE TITLE
Google Drive throttling corrupts existing files

### ISSUE THREAD

**Issue by tpet93** [fsantini/KoboCloud#126]
When accessing too many files using Google Drive, a temporary forbidden response is returned.
![image](https://user-images.githubusercontent.com/26135231/157626993-04c4989b-6534-4ed1-825b-1aed5336d21c.png)

This HTML page is currently written to the existing .epub regardless of status code, causing it to to become unreadable by the e-reader. 

I found it necessary to skip files if they exist, to not trigger the throttling after the first ~30 books.

I've posted a potential workaround  in [d8946c998ffc27baa665ef0960b2c72a4ed146ff](https://github.com/tpet93/KoboCloud/commit/d8946c998ffc27baa665ef0960b2c72a4ed146ff)

It may need some further edits to not interfere with other cloud providers (I've only tested with Gdrive)

EDIT: the above solution may have some issues with ever growing files / false-success status, needs work.

**Comment by groentebroer** [comment]
@tpet93 Please also see the note in the readme, for large folders.
Could it help to seperate the files across multiple share folders?
