### ISSUE TITLE
Google Drive sync randomly overwrites book

### ISSUE THREAD

**Issue by Jerther** [fsantini/KoboCloud#127]
Sometimes my kobo would randomly show the black importation screen with the progress bar. I did not bother but then it got scary. My girlfriend had the same behavior on her reader but then she noticed all the annotations in some of her synced books were gone!!! Hours of careful work, gone! The books were still there, but marked as unread.

I have a Kobo Glo and my girlfriend has a Kobo Libra. We use separate Google Drive accounts and shared folders, and we both have REMOVE_DELETED in the configuration, though we added that recently. It may have started when we added this option.

Now it's random, and scary, so I'm not sure where to go from here to provide more details.

**Comment by tpet93** [comment]
This could be the behavior described in #126.
if the books disappear or become unreadable again, plug the reader into the computer and look at the file sizes in the .add/Library folder.

If the books in question are around ~2kB it has been overwritten by an error message, another later sync should bring the book back.

As a quick workaround limiting the number of books in gdrive should help.

**Comment by Jerther** [comment]
The books are still readable. They are reset to "unread" and have lost all annotations. Just like they were deleted and synced again.

Also, there are fewer than 10 books in the shared folders.

It could be that kobocloud replaces the book by the error file, and replaces it again by the actual book in a subsequent sync. But in all cases, why would kobocloud **re**-sync a book...?

**Comment by groentebroer** [comment]
@Jerther the only way to verify if a book is "complete" on the device (not a broken download) is to verify if the file still exists and is the same as the remote.
Sadly the error handling is not good enough to detect a broken remote (e.g. Google throwing an error), filesize different means re-download to "fix" the issue with the book.
