### ISSUE TITLE
New kobo software issues?

### ISSUE THREAD

**Issue by Hamelscott** [fsantini/KoboCloud#13]
Ever since the new software release, my Kobo Clara HD is not playing nicely with kobocloud anymore. Books are pulled in in duplicate, and only about half the books?
Any testing been done to see if something is broken?
As an aside, I've read that the Kobo forma(?) Will now have native Dropbox support.

**Comment by fsantini** [comment]
Hi! Sorry to hear that. My kobo glo still seems to be working correctly, but I will see if I get any new update (it's a rather old device). In the meantime, can you please send me your .kobo/kobocloud/get.log file so I can try to figure out the problem? (please redact the URLs if you post it publicly)
