### ISSUE TITLE
Why i can not download book

### ISSUE THREAD

**Issue by andy10242421** [fsantini/KoboCloud#130]
why i can not download book
like this
![image](https://user-images.githubusercontent.com/86422356/161942873-22aec2cb-4c42-4eda-8c85-7fa7b74c4e67.png)

**Comment by fsantini** [comment]
Hi sorry I don't understand exactly the problem. The books are downloaded but are not imported?

**Comment by groentebroer** [comment]
They are all 1kb, which will probably not be enough. ;-)
Looking at the filenames, it has something to do with foreign characters in the filenames probably?

**Comment by andy10242421** [comment]
this only english? i used Punctuation and chinese

**Comment by andy10242421** [comment]
sorry  my englsih so bad

**Comment by andy10242421** [comment]
I uploaded it to dropbox and it didn't load when I synced it. The file name shows these strange numbers and English.

**Comment by andy10242421** [comment]
The file size in my DROPBOX is normal, but it is 1KB when uploaded here

**Comment by andy10242421** [comment]
Thank you, I change it to English and it will work
