### ISSUE TITLE
Sync without Login

### ISSUE THREAD

**Issue by krillin666** [fsantini/KoboCloud#132]
Hi there @fsantini !
Thank you so much for this amazing piece of software. However, I wanted to know if its possible to use KoboCloud without an account in the Kobo device.
I used the trick of editing the Kobo database with sqlite to trick the Kobo into thinking an account is setup, but no account is on the Kobo.
This in turn prevents me from syncing (since no account is present), which I'm afraid is also how the KoboCloud works.
Is there a way to make it sync the files without an account =

**Comment by fsantini** [comment]
Hi! Have you tried? We don't use kobo syncing, so it might just work!

**Comment by fsantini** [comment]
You should just enable wifi. The scripts detect when WiFi is on and download the books

**Comment by krillin666** [comment]
Sorry for my misunderstanding, it is indeed working ! Albeit it only works for one of the links I configured. The one working is for my nextcloud instance which has subfolder but only `epub`files. The other link I have is for a GDrive shared folder with many subfolders which have pdf's in them but also mp3 files.
Could the mp3 files be causing the problem ? I only want the pdf

**Comment by VPeeters** [comment]
Could you post your logs? Mp3s should not be a problem

**Comment by krillin666** [comment]
I'm sorry, its working now ! I must have messed up something in the setup :sweat_smile:
