### ISSUE TITLE
Unable to sync Box or Dropbox

### ISSUE THREAD

**Issue by grewgirl** [fsantini/KoboCloud#135]
I have a Libra 2 with firmware 4.31.19086

After adding the shared links to the kobocloudrc, I get Permission Denied for both cloud services. I did choose to share with anyone who has the link .

Also, the link for the Dropbox private folder (https://www.dropbox.com/oauth2/authorize?client_id=5oyw72cfwcp352f&response_type=token&redirect_uri=https://louisabraham.github.io/KoboCloud) results in Error 400 bad request.

**Comment by louisabraham** [comment]
can you try again?

**Comment by grewgirl** [comment]
Thanks - I have the Apps folder on my Dropbox account now.
 This is how the information presents on my screen - how much of it do I
need?

[image: image.png]



raise your words, not your voice. it is rain that grows flowers, not
thunder.
                                                    -rumi

**Comment by louisabraham** [comment]
I cannot see your picture. I don't think you can attach images in an email reply!

**Comment by grewgirl** [comment]
Ah, OK.

I was asking about the instructions - I have added everything after
'DropboxApp:' but my Libra2 isn't synchronizing with the dropbox folder
that was created. I've copied it the way that it rendered on my screen,
wrapped text and all.

curl -s https://api.dropbox.com/oauth2/token -d
grant_type=authorization_code -d client_id=5oyw72cfwcp352f -d redirect_uri=
https://louisabraham.github.io/KoboCloud/ -d
code_verifier=0000000000000000000000000000000000000000000 -d code=null |
sed 's/.*"refresh_token": "\([^"]*\)", ".*/\nAdd this line to your
kobocloudrc file:\n\nDropboxApp:5oyw72cfwcp352f:\1\n\n/'



Thanks. I figure since the other Dropbox and Box links aren't working, that
I may just have to load my Calibre library manually.

**Comment by louisabraham** [comment]
You may want to follow those instructions instead, they are the most recent ones and are waiting for the PR to be accepted: https://github.com/louisabraham/KoboCloud#dropbox-private-folder

**Comment by louisabraham** [comment]
Whay do you see when you click on this [link](https://www.dropbox.com/oauth2/authorize?response_type=code&token_access_type=offline&client_id=5oyw72cfwcp352f&code_challenge_method=plain&code_challenge=0000000000000000000000000000000000000000000&redirect_uri=https://louisabraham.github.io/KoboCloud/)?

**Comment by grewgirl** [comment]
I was able to retrieve the command and run it in Git Bash, but nothing happens when I add the generated informattion to kobocloudrc, eject/reset and sync. 

At present neither Dropbox option nor ther Box option work on my  Libra2 (firmware 4.33.19608).

**Comment by louisabraham** [comment]
That's because you need to build the latest version from my fork.

**Comment by grewgirl** [comment]
I've been following the instructions and links provided in this repo.

**Comment by grewgirl** [comment]
I was able to uninstall/reinstall kobocloud and now the connections are working.
