### ISSUE TITLE
Internal IP address

### ISSUE THREAD

**Issue by nussejj** [fsantini/KoboCloud#139]
Using Nextcloud on local network with local ip address does not sync properly. There are no errors in the log file and when using google drive as a test sync does work. Example address in kobocloudrc 

192.168.0.0/index.php/s/dj38kajd740kdj

Does this need to be formatted in a different way to work for internal networks?

**Comment by groentebroer** [comment]
And when using a valid IP, it might be needed to add "http://" in front of it.
