### ISSUE TITLE
Forcing content import

### ISSUE THREAD

**Issue by upward4** [fsantini/KoboCloud#140]
When adding a book to my Dropbox folder and tapping the "Sync now" button from the Kobo, the newly uploaded book does not appear. I have to reboot the device to trigger the "Importing content..." screen.

I tried forcing a rescan with NickelMenu's `rescan_books` and `rescan_books_full` actions, but none works. Is there any way to force content import?

**Comment by groentebroer** [comment]
For me it works to disable wifi and to turn it back on.

**Comment by fsantini** [comment]
the sync button has no influence on this script.

**Comment by upward4** [comment]
> the sync button has no influence on this script.

Is there any way to tell the script to download/import books on-demand?

**Comment by groentebroer** [comment]
https://github.com/fsantini/KoboCloud/issues/140#issuecomment-1170011565
