### ISSUE TITLE
Losing progress/annotations due to Google Drive sync

### ISSUE THREAD

**Issue by awchen** [fsantini/KoboCloud#144]
I'm wondering if it might be worth adding some functionality to error-check downloads to prevent the local ebook file from getting overwritten by a Google error page. I'm happy to do some work on this, as I've just lost a decent number of annotations and don't want this to happen in the future.

Two potential angles of attack:

1. Easier, more hacky: special-case/create a heuristic for the Google Drive error screen and don't download the file if it matches.

2. More complex, introduces new functionality: check the diff of the file and don't download if there's a difference (apart from deletion). Therefore, a user would need to rename the ebook in order to get it to redownload.

**Comment by groentebroer** [comment]
Hi @awchen Currently we have no implementation for that.
Our use-case is to facilitate the "automatic" download of e-books without having to use the store application. Annotations are probably stored within the database and not within the ebook itself (not verified), which is not something we connect to. The DB displaying the ebook and notes is handled by the Kobo OS still.
