### ISSUE TITLE
Correcting wrong WebDAV url 

### ISSUE THREAD

**Issue by bmxam** [fsantini/KoboCloud#15]
Hi Francesco,
First thank you for your great program. It worked almost perfectly in my case. Why 'almost'? I wanted to use a free folder on my own Nextcloud server,. The server has the given url : https://example.com/nextcloud
Your original program (getOwncloudFiles.sh) was trying to download the files through the following webdav url (information read in the get.log):
https://example.com/nextcloud//nextcloud/public.php/webdav/file.pdf
instead of
https://example.com/nextcloud/public.php/webdav/file.pdf
So I slightly modified the source getOwncloudFiles.sh to modify the `linkLine`. Just before`'linkLine=...` I set ``relativeLink=`echo $relativeLink | sed 's/nextcloud\///g'` `` to remove "nextcloud/" from the `relativeLink`.
Now it works great.
Since I suspect that the problem is specific to my server url (https://example.com/nextcloud), I prefer not to propose a merge request, I let you find the correct way to fix this bug.
Best regards,
Maxime

**Comment by fsantini** [comment]
Thanks, I'll check it out! I was swamped with other things, but now I have a working Nextcloud installation (which I didn't have before) so I can do some better debugging.
