### ISSUE TITLE
Files downloading but not showing up on Kobo

### ISSUE THREAD

**Issue by elijahbarron** [fsantini/KoboCloud#153]
I set up KoboCloud syncing from Google Drive.

When I plug my Kobo into the computer, the .epub books show up
.add>kobocloud>Library so they definitely downloaded

But they do not show up on my Kobo

**Comment by groentebroer** [comment]
This is not part of Kobocloud, This his part of the Kobo OS, to detect changed files.
After a restart are the files then shown?
Otherwise there seems to be something wrong with the Kobo OS, not detecting the file change.

**Comment by DenizAsker** [comment]
Hi,
This thread may help...

[https://github.com/fsantini/KoboCloud/discussions/148]
