### ISSUE TITLE
Kepub format automatically converted to Epub

### ISSUE THREAD

**Issue by J0ssel1n** [fsantini/KoboCloud#173]
It's all in the title. I put a book on Google Drive, the e-reader downloads it but first the books don't appear, and when I plug in the computer and go to /Volumes/KOBOeReader/.add/kobocloud/Library I see that the books are downloaded. So when I unplug I see on my e-reader (which is a Kobo Libra H2O) the screen that imports the books. BUT the books are in EPUB format and not KEPUB which offers more features. But thank you for offering the possibility of syncing my e-reader with Google Drive. Just fix a few bugs to provide a perfect experience.

<img width="1071" alt="Capture d’écran 2024-02-11 à 19 25 04" src="https://github.com/fsantini/KoboCloud/assets/92841489/a1424460-a2b1-4dea-85f8-19885f96e16d">

**Comment by fsantini** [comment]
Hi. The scripts do not change the content of the books. It's normal that Kepub books still have the epub extension. They will still be kepub if you have uploaded to google drive as such.
