### ISSUE TITLE
Issue syncing large google drive directories

### ISSUE THREAD

**Issue by desyncr** [fsantini/KoboCloud#18]
Before anything: thank you for the work invested in this project!

Now on the issue: I have used the google drive integration without problem for months. Recently I started to experience issues syncing.

Taking a look at the sync process I noticed two issues:

- Google drive detects multiple downloads on a row and complains as follows:
```
Your computer or network may be sending automated queries.
To protect our users, we can't process your request right now
```
The sync process does not detect this error and saves it as the book contents. Further sync wont work as the file appears downloaded and the remoteSize is not obtained and defaults to 1 (the content previously saved size is 1k).

- The sync process seems to take longer than it's expected and is stopped before it finished. I noticed this looking at the logs and seeing that the lasts files wont get synced (it processes items in alphabetical ascending order).

I have logs if that helps. Some details to reproduce: 70 files, averaging 1.5Mb each.

My intention is to use this shared directory for permanent storage for my books, rather than to use it as a temporary place for syncing.

**Comment by bagcivan** [comment]
Yes lately it is not working for google drive. @fsantini can you help us

**Comment by fsantini** [comment]
I'll try to have a look over the weekend!

**Comment by desyncr** [comment]
Thanks @fsantini let me know if I can help with anything. I was thinking of having a sort of cache (but that sounds like more problems).

**Comment by desyncr** [comment]
@fsantini Something I noticed that's happening (that's not related to large directories) is that Google Drive is returning the following:
```
<HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="...">here</A>.
</BODY>
</HTML>
```
I'm testing a quickfix using `curl -L`.

**Comment by mmmx10** [comment]
If thi can help...

I actually can get files from dropbox and not from drive, on Libra.

Looking at the get.log files it seems kobocloud can't get the filelist inside the folder of drive, so the getting line always write the folder shared link (in the log from dropbox I find filenames after the shared link)

**Comment by desyncr** [comment]
I tried with Dropbox and had no issues. Do you have many ebooks there? Can you share the log (remove any personal information)?

**Comment by mmmx10** [comment]
I don't have problems with dropbox but with gdrive
this is the log for drive
[get-drivekoe.log](https://github.com/fsantini/KoboCloud/files/4695951/get-drivekoe.log)
this the log for dropbox
[get-example.log](https://github.com/fsantini/KoboCloud/files/4695959/get-example.log)

In the first one you don't have filenames of files, only the hash of the folder...

**Comment by desyncr** [comment]
@mmmx10 The issue is that you got an extra character on the URL:

<img width="563" alt="Screen Shot 2020-05-31 at 15 16 27" src="https://user-images.githubusercontent.com/1857707/83359616-b609de80-a351-11ea-8bde-1d210582b357.png">

Remove that `^M` (carry return) and it should work. You may have to change the line-ending in whatever text editor you're using.

See [this](https://www.networkworld.com/article/3107972/windows-vs-unix-those-pesky-line-terminators.html) and [this](https://superuser.com/questions/473614/vim-shows-m-symbols-and-they-arent-disappearing).

**Comment by tpet93** [comment]
I found issues whith syncing when i had square brackets "[" in the filenames on Gdrive

**Comment by desyncr** [comment]
Yeah, I think I've seen similar issues before. I'll try it out later. Thanks for the report.
