### ISSUE TITLE
Not working for recent Kobo?

### ISSUE THREAD

**Issue by therourke** [fsantini/KoboCloud#2]
I would love to be able to sync directly from Dropbox, but KoboCloud doesn't seem to work on latest firmware. Any chance of an update?

Thanks

**Comment by fsantini** [comment]
Hi! Well I haven't maintained it in a long time, but I'll see what I can do... Follow this issue and I'll report the progress here!

**Comment by therourke** [comment]
Thanks for the fast reply! Fingers crossed you can get it working again. I would adore this feature.

**Comment by fsantini** [comment]
So well it turns out that the problem is curl, which segfaults whatever I do... I tried recompiling a more recent OpenSSL and Curl, but still same result. Unfortunately I don't have time to try harder at the moment, if anybody would like to give it a go, be my guest.

**Comment by cburschka** [comment]
I see the segfault as well... is there a way to see more detailed output? Or a way to run the Kobo firmware in some kind of sandbox on a Linux desktop?

My first suspicion would be that some standard library is either missing or incompatible with whatever curl was compiled against, maybe...

**Comment by cburschka** [comment]
I found a potential solution for running curl on Kobo firmware, which I'll test when I next get the opportunity:
 https://www.mobileread.com/forums/showthread.php?p=3734553

**Comment by fsantini** [comment]
That would be awesome!

**Comment by cburschka** [comment]
Using the curl binary from the link, I was indeed able to download URLs.

Unfortunately, the next issue is that the NextCloud script seems to be out of date, and relying on static HTML. As far as I can tell, it's no longer possible to access NextCloud web pages that way, since they use client-side rendering now. The only API offered by NextCloud is WebDAV, which unfortunately doesn't work with public shared folders (it requires password authentication).

I'm going to try to circumvent this by downloading the folder as a zip file, but that's going to become impractical quickly as the library grows... :/

**Comment by fsantini** [comment]
This is really good news! Dropbox had a similar problem, but I was able to go around it. I would need access to a current NextCloud folder though, would you be able to set one up for me? Just with any text file inside. I only have an old ownCloud installation and I don't feel like upgrading any time soon.

**Comment by fsantini** [comment]
Great! Thanks! Would you mind creating a small text file in it?

**Comment by cburschka** [comment]
Oh right! Yeah, there's a test.txt in it now.

**Comment by fsantini** [comment]
OK it works! (Well at least on my PC) You can find the directory listing with:
```
curl -i -X PROPFIND -u kXExESE97ryCLso: https://cloud.burschka.de/public.php/webdav/ --upload-file - -H "Depth: 1" <<end
<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:">
<a:prop><a:resourcetype/></a:prop>
</a:propfind>
end
```

and get the file with 
`curl -u kXExESE97ryCLso: https://cloud.burschka.de/public.php/webdav/test.txt`

Note that you pass the user with -u and the user name is the directory name in the link.

I'm going to implement this when I have some time!

**Comment by fsantini** [comment]
Ok it seems to be working! Thanks for your help!
