### ISSUE TITLE
Stop working on a kobo aura hd

### ISSUE THREAD

**Issue by rlore69** [fsantini/KoboCloud#22]
Hi, I'm using your tool on a kobo aura hd for several months, and I must thank yop for your very good work, but since a week afther a kobo firmware upgrade it's stop working. I have done a full reset of the device and now I'm not able to reinstall it. When I put the KoboRoot file afther the reset I'don't find the kobocloud directory.
Can ou help me ?

Thanks in advance Lorenzo

_

**Comment by fsantini** [comment]
Did you try looking under `.add` instead of `.kobo`? This changed a while ago to avoid duplicate books in the library.

**Comment by rlore69** [comment]
Thank you very much for your help ... I've not seen this change !!!
