### ISSUE TITLE
Re-downloading existing books?

### ISSUE THREAD

**Issue by tpet93** [fsantini/KoboCloud#25]
Please correct me if wrong but does the script not try to download the entire library on each update.
would adding a check such as 
```bash
FILE=$localFile
if [ -f "$FILE" ]; then
    echo "$FILE exists."
else 
    echo "$FILE does not exist."
fi
```
to getRemoteFile.sh greatly improve performance when the cloud library is very large?

**Comment by fsantini** [comment]
Mmm I think that this must be a regression from when we removed the size check for existing books. I feared that something like this would happen. I will look into it.

**Comment by groentebroer** [comment]
@fsantini Is this issue still there?

What was the issue with the file size check? Because @VPeeters suggested filesize as a solution to resolve copies of the same books from different download URL's...

**Comment by fsantini** [comment]
I think I checked and couldn't replicate. Curl should avoid downloading a file if it already has the right size. Maybe this happens in cases when byte ranges don't work. Another quick check would be good.

**Comment by louisabraham** [comment]
Indeed, this is the `-C -` option https://curl.se/docs/manpage.html#-C
