### ISSUE TITLE
Books do not sync automatically from google drive

### ISSUE THREAD

**Issue by princensuuu** [fsantini/KoboCloud#28]
Hi,

I needed to restart my device every time, in order to see latest uploaded collection. It was not doing automatic sync.

**Comment by VPeeters** [comment]
I've got this issue too..

**Comment by groentebroer** [comment]
The script currently only runs at startup and then tries it several times before WiFi becomes available.
After that the script is indeed not run anymore, until the next restart.

**Comment by VPeeters** [comment]
Ah I see. Or everytime Wifi is enabled. That would also trigger the udev rule. It would be great if there'd be a way to trigger the scrypt upon using the sync function on Kobo.

**Comment by kirtr** [comment]
The behavior on my device is that I had to reboot after updating my configuration file. Now that KoboCloud has reread my updated configuration file it is syncing properly for me.

**Comment by cavriends** [comment]
First off, installing it was a breeze and the first sync was flawless. However, I also experience the same issue as mentioned above. After dropping new epubs in GDrive it doesn't sync immediately (even after turning it on and off, switching wifi on and off). The books pop up at a random time after I've dropped them in GDrive. Perhaps hooking to the Kobo sync button would be awesome!

**Comment by VPeeters** [comment]
> First off, installing it was a breeze and the first sync was flawless. However, I also experience the same issue as mentioned above. After dropping new epubs in GDrive it doesn't sync immediately (even after turning it on and off, switching wifi on and off). The books pop up at a random time after I've dropped them in GDrive. Perhaps hooking to the Kobo sync button would be a great solution. Besides this, awesome work!

Yeah it would be... But I do not know a solution to achieve this.
