### ISSUE TITLE
Books in dropbox folder not showing up on ereader

### ISSUE THREAD

**Issue by Ttwyman** [fsantini/KoboCloud#30]
I've just installed the kobocloud on my kobo Clara and have put a epub book into the folder however it is not showing on my ereader even after restarting the device a few times.
This is my first time using code or github so I'm not sure if I have done everything correctly.

**Comment by tylpk1216** [comment]
Did you have "/mnt/onboard/.add/kobocloud/get.log" file in your kobo device ?

If you could show the content of this file, I can check what is your problem.

**Comment by Ttwyman** [comment]
No I can't find that on my e-reader. On 3 Jul 2020 4:33 am, Michael Kuo <notifications@github.com> wrote:
Did you have "/mnt/onboard/.add/kobocloud/get.log" file in your kobo device ?
If you could show the content of this file, I can check what is your problem.

**Comment by tylpk1216** [comment]
Could you check steps below to compare with your previous installation?

01. Use official release (https://github.com/fsantini/KoboCloud/releases/download/0.5/KoboRoot.tgz), you could use your complied item.
02. Put this tgz file to the folder (.kobo) of your kobo device.
03. Restart your kobo device.
04. Add your link to the file (.add/kobocloud/kobocloudrc), remember add newline behind your link string.
05. Restart your kobo device again.

It should have log now.

**Comment by remissao** [comment]
@tylpk1216 

I have the same problem on Kobo Touch. The files are downloaded into .add/kobocloud/Library but they don't show up on the "My Books" section on the main Menu.

**Comment by tylpk1216** [comment]
@remissao 

I do not have any kobo devices so I need the log to check what happened.

If your installation was right and your device does not have the log, I will guess the KoboRoot.tgz is not compatible to Kobo Touch.

**Comment by Ttwyman** [comment]
I have all the files and also don't have that file on my ereader, but mine
is a kobo Clara so quite a new one.
I've uninstall it at the moment and will try again when I get the chance.

**Comment by tylpk1216** [comment]
@Ttwyman 

Your problem is like https://github.com/fsantini/KoboCloud/issues/29#issuecomment-653978269

If you know how to write shell script, you could add some debug message to check  what happened.

**Comment by Ttwyman** [comment]
I dont know how to write any script

**Comment by eleccy1** [comment]
My problem is some epub files show in my books some do not. I've used both dropbox and google drive to download. I'm not a coder so I'm hoping someone can help.

**Comment by Falmer** [comment]
> 4\. remember add newline behind your link string.

This and updating my system to the last version made the difference for me. The script now work correctly.

**Comment by groentebroer** [comment]
Great, will close the issue!
