### ISSUE TITLE
Not downloading with Google Drive

### ISSUE THREAD

**Issue by cjmverweij** [fsantini/KoboCloud#31]
Hi there, followed the steps but I don't see anything happening.

my log shows the following:

```
2020-06-30_16:49:02 waiting for internet connection
Reading # Add your URLs to this file
Comment found
Reading # Remove the # from the following line to uninstall KoboCloud
Comment found
Reading #UNINSTALL
Comment found
Reading # Google Drive
Comment found
2020-06-30_16:49:08 done
```

It seems like maybe it's not recognizing or reading the link I've put in the `kobocloudrc` file?

any help would be appreciated (and thanks for all the hard work so far!)

**Comment by tylpk1216** [comment]
![url](https://user-images.githubusercontent.com/14836065/86236621-f963a100-bbcc-11ea-8c2a-b8f028e78973.png)
The "get.sh" file is to check your $url setting and to get files from your settng. It seems that it can not find the $url to work. Do you add $url(no "#" comment character) in ".add/kobocloud/kobocloudrc" of your Kobo device?

**Comment by tylpk1216** [comment]
By the way, $url is every line that reads from kobocloudrc. If your file includes any string that does not start from '#' character, the $url variable will be valid.

**Comment by cjmverweij** [comment]
so this is in my kobocloudrc:
`
# Add your URLs to this file
# Remove the # from the following line to uninstall KoboCloud
#UNINSTALL
# Google Drive
https://drive.google.com/drive/folders/1_dlf3Ry8c5lCP8In4-k_LOGzFfgrHUs5?usp=sharing
`
So it seems like it's skipping over the last line?

**Comment by tylpk1216** [comment]
Caution: your link of GoogleDrive is public. Please turn it off and change another new folder for your kobo devixe.

If your guess is right, you could add "enter character" to the last line. Maybe it will work. Just guess because I do not have any kobo devices to verify it.

By the way, do you have another Linux machine? This project can also run on Linux. You can test it to check whether it works or not.

**Comment by cjmverweij** [comment]
you mean like so?
```
# Add your URLs to this file
# Remove the # from the following line to uninstall KoboCloud
#UNINSTALL
# Google Drive
https://drive.google.com/drive/folders/<id>?usp=sharing
enter character
```
Don't have a linux machine unfortunately..

**Comment by cjmverweij** [comment]
That actually worked 👍

Thanks a lot for your helm, really great 🍻

**Comment by tylpk1216** [comment]
Congratulations !

I also searched Google to get the answer why the last line can not be read ? I also got a new knowledge for your question. 

[https://unix.stackexchange.com/questions/169716/why-is-using-a-shell-loop-to-process-text-considered-bad-practice](https://unix.stackexchange.com/questions/169716/why-is-using-a-shell-loop-to-process-text-considered-bad-practice)

**Comment by digitaleye62** [comment]
Hello
this is what my "koboclodrc" file looks like after modifying it:
[https://i.postimg.cc/nVPPL1zx/Schermata-2022-10-17-alle-11-29-53.png](url)
what am I wrong?
thank you
