### ISSUE TITLE
line 16: /usr/local/kobocloud/curl: Permission denied

### ISSUE THREAD

**Issue by AlbertoFabris01** [fsantini/KoboCloud#33]
I tried twice to follow the instructions but in the log it seems like it can't open the google drive folder

2020-07-06_14:10:09 waiting for internet connection
Reading # Add your URLs to this file
Comment found
Reading # Google drive:
Comment found
Reading ...
Getting ...
Getting ...
/usr/local/kobocloud/getGDriveFiles.sh: line 16: /usr/local/kobocloud/curl: Permission denied
Reading # Remove the # from the following line to uninstall KoboCloud
Comment found
Reading #UNINSTALL
Comment found
2020-07-06_14:10:20 done

**Comment by tylpk1216** [comment]
Caution: Remember to hide your URLs in the log. These URLs are public.

Could you try the release file ? The compiled step is an optional. If you did not compile file on Linux, it will have problems sometimes.

**Comment by AlbertoFabris01** [comment]
No problem, there were no secrets there :)

It worked: I think that the problem was the compile step, now it works.

Thanks ;)
