### ISSUE TITLE
Is this applicable to Kobo Aura edition 2?

### ISSUE THREAD

**Issue by amordesoul** [fsantini/KoboCloud#38]
Hi - I have .tgz file ready to go .kobo (1) folder but the (1) is not showing. I've enabled viewing of hidden files.

I tried just copying the .tgz file into the .kobo folder.  After disconnecting the device it rebooted. But after the reboot was finished, the .tgz file was gone and I have no way of opening ".add/kobocloud/kobocloudrc"

Is my Kobo firmware just too old for this hack?

**Comment by groentebroer** [comment]
@amordesoul It should work even on your device.
Please let me know if you got it resolved, otherwise please try a recent version from the releases.
We will close it for now, feel free to open a new ticket if you still have any issues.
