### ISSUE TITLE
HTTP server doesn't seem to support byte ranges. Cannot resume.

### ISSUE THREAD

**Issue by trvrcr** [fsantini/KoboCloud#41]
{ [5 bytes data]
< HTTP/1.1 500 Internal Server Error
< Server: nginx
< Date: Fri, 30 Oct 2020 18:55:46 GMT
< Content-Type: application/xml; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: ocrhj9gbj1qb=qg7etvgtcl3p2majp6i0fo950u; path=/; secure; HttpOnly; SameSite=Lax
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=kVltJDbkMeV4EfJsQ2zE8IZ0k734VD0s%2FfNyrxwNcdNSxbkHKiLE9QmZQ4yUGMGF7TlTseL9mOqZr6e0ZPv500Ewuc81s%2Fkgixfo7gzZabixEkxXbW04UCMQhJxTUYOs; path=/; secure; HttpOnly; SameSite=Lax
< Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-QWkwZG84YlI4OW1HUWZFbk0xWmY0MGQ2dFVITjYrRGtTWEVLWmJ5RTJPbz06VWt3dTh2ZWtvNDMzSnFZTVZXTWRyRGMzMWlmaW83VytBQ0UvVitieWpaZz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
< Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< X-Robots-Tag: none
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: no-referrer
< X-Frame-Options: SAMEORIGIN
< 
* HTTP server doesn't seem to support byte ranges. Cannot resume.
* Closing connection 0
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
Remote file information:
  Status code: 500
Error: Server error

**Comment by trvrcr** [comment]
So I found the problem:
In the log file I found the next line.
Download: /usr/local/kobocloud/curl --cacert "/usr/local/kobocloud/ca-bundle.crt" -u REDACTED: -k --silent -C - -L -o /mnt/onboard/.add/kobocloud/Library/REDACTED.epub https://REDACTED.com//public.php/webdav/REDACTED.epub -v

in the command 2 // before public.php instead of only 1

looking in code where it is created

**Comment by VPeeters** [comment]
Fixed in #70
