### ISSUE TITLE
KEPUB not synced

### ISSUE THREAD

**Issue by Varming73** [fsantini/KoboCloud#42]
I've set up sync with Google Drive and Dropbox but KEPUB files are not synced to my device, only EPUB files. As KEPUB is the Kobo format I would have expected it to work. Is it an error or is KEPUB not supported?

**Comment by fsantini** [comment]
Hi! Kepub books should have the `.kepub.epub` extension as per https://wiki.mobileread.com/wiki/Kepub

> Note that a kepub formatted book needs the extension to be .kepub.epub, that is two extensions. Otherwise it will not recognize the book as different from a normal epub.

**Comment by Varming73** [comment]
Mobileread is down - I can't enter it (as the only site) so I can't read there. I've had my Kobo for several years and books bought from the Kobo store have extension .kepub and Calibre converts to KEPUB with extension .kepub by default so I've never seen two extensions for KEPUB files before (even though having been with Kobo for years).

**Comment by fsantini** [comment]
Can you post your get.log file (delete the urls before uploading)? I think that the files should be downloaded but not recognized by Kobo. I can write some code to automatically rename the files if needed, but I am unsure about your current workflow so I can't decide on the best course of action. The .kepub.epub extension is also mentioned in the kobo github for sideloading, which is practically what we are doing: https://github.com/kobolabs/epub-spec

**Comment by Varming73** [comment]
[get.log](https://github.com/fsantini/KoboCloud/files/5493836/get.log)

There you go. I'm sure it's a limitation in Calibre somehow and it would be great if the file could be renamed automatically if you don't support .kepub which Calibre generates when converting from some format to KEPUB.

**Comment by Varming73** [comment]
I just saw the the .kepub files are actually in the .add/kobocloud/Library folder... strange.

I wonder if Calibre add the right extension when I in Calibre choose send to device. Would be really strange but who knows.

**Comment by fsantini** [comment]
Calibre might register the file directly with the Kobo database when you send it to the device, or rename it appropriately. But I can change the code to have it append epub automatically. When I have some time I will do it.

**Comment by Varming73** [comment]
That sure would be great, thanks!

**Comment by Varming73** [comment]
I just came across this info om Mobilereads:
"Note that in Calibre, when you try to Send books to your kobo, Calibre will first convert the epub books (using kepub output plugin) to .kepub.epub in temporary directory in you PC and then send the .kepub.epub file to your kobo, after that, Calibre will delete the temporary directory."

So you're totally right, Calibre does some dirty "magic" behind the scenes to make things work with the .kepub. Why it doesn't just work with the right extension from the beginning is a bit strange but it is what it is. Would be great if you could do the renaming!

**Comment by groentebroer** [comment]
@fsantini I think this is already in the `getRemoteFile.sh` right?
So we can close this one?

```# add the epub extension to kepub files
if echo "$localFile" | grep -Eq '\.kepub$'
then
    localFile="$localFile.epub"
fi
```

**Comment by fsantini** [comment]
Yes you are right we can close it.
