### ISSUE TITLE
Files with apostrophes do not sync

### ISSUE THREAD

**Issue by aaronson2012** [fsantini/KoboCloud#44]
When attempting to sync the file: "Harry Potter and the Sorcerer's Stone - J. K. Rowling.epub", the file is not synced and instead a file named "Harry Potter and the Sorcerer" is created in the kobocloud library folder.

**Comment by Primerius** [comment]
Same issue using [ ], which I like to use to indicate a series in the filename. So Tamsyn Muir - [Ninth House 01] - Gideon the Ninth.epub becomes a file named "Tamsyn Muir - "

**Comment by fsantini** [comment]
Uhm... I thought that it would be an easy fix, but this shouldn't happen and I don't understand exactly why it does. Can you please post your (redacted) get.log fine?

**Comment by mxbndr** [comment]
I can anecdotally confirm this.

"The Hitchhiker's Guide to the Galaxy - Douglas Adams.epub" does not work on Google Drive or Dropbox
"Parable of the Sower - Octavia E. Butler" works on both

The KoboCloud library folder acquires a title called "The_Hitchhiker"

The problem is solved if I just remove the apostrophes from the file title via a file explorer (e.g. Finder on macOS).

**Comment by mxbndr** [comment]
I would happily add a get.log file. Should I redact all identifiable information (e.g. Dropbox links)? Or do you need certain things?

**Comment by fsantini** [comment]
Hi! Yes please remove the links! Thanks!

**Comment by mxbndr** [comment]
[get.log](https://github.com/fsantini/KoboCloud/files/5711052/get.log)

This is a log with the example of "The Hitchhiker's Guide to the Galaxy - Douglas Adams.epub" on Google Drive

**Comment by mxbndr** [comment]
[The_Hitchhiker.zip](https://github.com/fsantini/KoboCloud/files/5711076/The_Hitchhiker.zip)

Here is an example of the file that gets created in kobocloud-->Library 

(I had to zip it to upload, but it's the file inside the zip)

**Comment by davcec** [comment]
Confirmed _GDrive_ do not properly synch if filenames contain [ ].

**Comment by VPeeters** [comment]
This should be fixed in the latest version
