### ISSUE TITLE
Not working with Libra H20

### ISSUE THREAD

**Issue by dhw1977** [fsantini/KoboCloud#45]
Just installed on a new Kobo Libra H20 and can't get sync to work with Google Drive or drop box.

The kobocloud.rc file is configured as follows

#Add your URLs to this file
#Remove the # from the following line to uninstall KoboCloud
#UNINSTALL
#Dropbox
https://www.dropbox.com/sh/96dcb0xxxxxxxxxxxxx03y4fRa7mulHKa?dl=0

The get.log says

2020-11-21_17:25:56 waiting for internet connection
Reading # Add your URLs to this file
Comment found
Reading # Remove the # from the following line to uninstall KoboCloud
Comment found
Reading #UNINSTALL
Comment found
Reading #Dropbox
Comment found
2020-11-21_17:26:07 done

I tried first by compiling the tgz file on my windows laptop.  This failed so I uninstalled kobocloud and used the ready compiled tgz file.  

This still doesn't work.

Any ideas?

Thanks.

**Comment by fsantini** [comment]
Hi! Try removing the ?dl=0 at the end of the link and/or adding a blank line after the link.

**Comment by dhw1977** [comment]
> Hi! Try removing the ?dl=0 at the end of the link and/or adding a blank line after the link.

Brilliant!!  Thank you - doing both fixed it.

Thank you for this - such a useful tool.

David
