### ISSUE TITLE
OVERDRIVE NOT WORKING AGAIN

### ISSUE THREAD

**Issue by Megaman222111** [fsantini/KoboCloud#47]
Overdrive stopped working as soon as I installed this and even when I uninstalled it, overdrive was still not working.

**Comment by mxbndr** [comment]
FWIW, Overdrive is working normally for my Kobo Libra H2O with the latest install of KoboCloud.

**Comment by Megaman222111** [comment]
for me the browsing page in the overdrive section is stuck on please wait, but u can access it by searching from the search bar.

**Comment by Megaman222111** [comment]
i am currently using the kobo clara hd
