### ISSUE TITLE
Should the links to the cloud services be entered twice?

### ISSUE THREAD

**Issue by rei-vilo** [fsantini/KoboCloud#48]
According to the procedure, links to the cloud services are mentioned twice: first 

> **[Compiling](https://github.com/fsantini/KoboCloud#compilling)**
> 
> - Move to the project directory root
> - Open the configuration file located at src/usr/local/kobocloud/kobocloudrc.tmpl
> - Add the links to the cloud services (see the configuration example that follow below)

and then 

> **[Configuration](https://github.com/fsantini/KoboCloud#configuration)**
> 
> After following the installation process:
> - Plug your Kobo back into the computer
> - Open the configuration file located at .add/kobocloud/kobocloudrc
> - Add the links to the cloud services (one per line)

Should the links to the cloud services be entered twice?

Thank you!

**Comment by trigooo** [comment]
No, if you tried doing that you would see that the link is already there. Configuration is for changing the link you added in the installation process or adding new links.
