### ISSUE TITLE
Nextcloud not working on Libra H2O

### ISSUE THREAD

**Issue by aniqueta** [fsantini/KoboCloud#49]
Hi @fsantini Thanks for creating this. I'm struggling to get these scripts to work on a Libra H2O running software version 4.25.15875 (dated 11/9/2020) and Nextcloud 20.0.4. 

Here's my config:
```
# Add your URLs to this file
# Remove the # from the following line to uninstall KoboCloud
#UNINSTALL
# Nextcloud:
https://cloud.myserver.com/s/RaNDoM1234567
```

And the log:
```
2020-12-24_11:12:49 waiting for internet connection
Reading # Add your URLs to this file
Comment found
Reading # Remove the # from the following line to uninstall KoboCloud
Comment found
Reading #UNINSTALL
Comment found
Reading # Nextcloud:
Comment found
2020-12-24_11:13:00 done
```

Per the log, it does not appear there was any attempt to 'read' or 'get' anything at my URL. There are no spacing issues. 

When I look at DNS queries from the Kobo, it looks like the internet check with aws.amazon.com is attempted, as there is a DNS lookup for that, but there is never any DNS lookup for cloud.myserver.com. 

There are no issues accessing the Nextcloud shared folder from other devices. 

I've tried running the scripts on my computer to debug, but I don't think it will work on other devices? For example, I ran getOwncloudList.sh with some modifications to make it more verbose. The cURL receives XML with this error: Sabre\DAV\Exception\NotAuthenticated. Again, I don't think the script is even getting this far, since there's nothing in the log to say it read the Nextcloud URL. 

I also tested it with Dropbox (not shown above) and that worked, so the issue appears isolated to how Nextcloud works. 

Help much appreciated.

**Comment by groentebroer** [comment]
@aniqueta I had the same issue.
I had to add an extra (empty or comment) line below the URL to make it work.
(I do not know why that might differ from DropBox though....)

**Comment by aniqueta** [comment]
Thanks. @groentebroer. I ended up switching to Kobo sync with [calibre-web](https://github.com/janeczku/calibre-web).

**Comment by VPeeters** [comment]
My Libra H2O also did not work with OwnCloud (similar to NextCloud) until I made some changes (#70 ).
