### ISSUE TITLE
Exclude certain file types?

### ISSUE THREAD

**Issue by scsmartt** [fsantini/KoboCloud#5]
Hi there! Thanks for keeping this going. I find it very useful! 
I was wondering if you could add a way to exclude certain filetypes or specify only certain filetypes to sync? For me, my books include metadata files and those get synced too and clutter up the library. It would be neat to specify to only sync kepub files for instance.

Thanks!

**Comment by scsmartt** [comment]
The reason I closed this is because I found a way to save my books to a folder minus the extra metadata files.

**Comment by fsantini** [comment]
Thanks for the comment! It's a very good suggestion and I will implement it!
