### ISSUE TITLE
cbz/cbr downloaded but not showing up in My Books

### ISSUE THREAD

**Issue by herrpina** [fsantini/KoboCloud#53]
I added the link of my Google Drive to the config file. The log files show that it finds the link and downloads my 2 cbz files. They are also downloaded and present in **.add/kobocloud/library**

But when going to my library of my Kobo, it doesn’t show up in the list... When I add a simple PDF to the Google Drive, it does show up. I added the same cbz file directly on the mounted drive when plugging in my Clara and it DOES show up that file. So it’s not a corrupted or unreadable file for my Kobo...

I tried a one page CBZ file with Kobocloud and that one appears. Could it be that my cbz-file is too large? It’s about 150MB

**Comment by herrpina** [comment]
When I connect my Kobo and look intothe .library folder, I see my pdf downloaded, and the two cbz files are both only 3kb...

**Comment by herrpina** [comment]
Doing another attempt, just used a new Kobo Libra. Did the same steps but on the Libra, it syncs the bigger files and not the smallers ones that synced on the Clara. Looking at the logs I see this difference, maybe it could help...

> File info: x5bx2218RWWtCaveyJVyHLPu5btJfFxqQ5VsZHFx22,x5bx221UtHjEPCEAEFr6NFlqRXnoi7BdD-woCXhx22x5dn,x22Archive3.cbz
File code: 18RWWtCaveyJVyHLPu5btJfFxqQ5VsZHF
File name: Archive3.cbz
Download: /usr/local/kobocloud/curl --cacert "/usr/local/kStatus: 0

> File info: x5bx221N1zGNdDGKUUzA-WS3DBW0FPsvRaPiIayx22,x5bx221UtHjEPCEAEFr6NFlqRXnoi7BdD-woCXhx22x5dn,x22Oog-In-Oog - 01 - Hitler Vs Stalin.cbr
File code: 1N1zGNdDGKUUzA-WS3DBW0FPsvRaPiIay
File name: Oog-In-Oog - 01 - Hitler Vs Stalin.cbr
Download: /usr/local/kobocloud/curl --cacert "/usr/local/kobocloud/ca-bundle.crt" -k --silent -C - -L -o /mnt/onboard/.add/kobocloud/Library/Oog-In-Oog_-_01_-_Hitler_Vs_Stalin.cbr https://drive.google.com/uc?id=1N1zGNdDGKUUzA-WS3DBW0FPsvRaPiIay&export=download -v
Status: 0

**Comment by herrpina** [comment]
Doing another attempt, just used a new Kobo Libra. Did the same steps but on the Libra, it syncs the bigger files and not the smallers ones that synced on the Clara. Looking at the logs I see this difference, maybe it could help... there's a big difference in the download section (set in bold)

> File info: x5bx2218RWWtCaveyJVyHLPu5btJfFxqQ5VsZHFx22,x5bx2222x5dn,x22Archive3.cbz
File code: 18RWWtCaveyJVyHLPu5btJfFxqQ5VsZHF
File name: Archive3.cbz
**Download: /usr/local/kobocloud/curl --cacert "/usr/local/kStatus: 0**


> File info: x5bx221N1zGNdDGKUUzA-WS3DBW0FPsvRaPiIayx22,x5bx22x22x5dn,x22Oog-In-Oog - 01 - Hitler Vs Stalin.cbr
File code: 1N1zGNdDGKUUzA-WS3DBW0FPsvRaPiIay
File name: Oog-In-Oog - 01 - Hitler Vs Stalin.cbr
**Download: /usr/local/kobocloud/curl --cacert "/usr/local/kobocloud/ca-bundle.crt" -k --silent -C - -L -o /mnt/onboard/.add/kobocloud/Library/Oog-In-Oog_-_01_-_Hitler_Vs_Stalin.cbr https://drive.google.com/xxx&export=download -v
Status: 0**

**Comment by danisuba10** [comment]
Same issue

**Comment by groentebroer** [comment]
Could you run the local test somewhere with your Google URL?
See: local_test.sh in the source.

Have you installed the release package or build it yourself. The execute permission bit might miss if installed yourself?
See: #31 as well.
