### ISSUE TITLE
subfolder support

### ISSUE THREAD

**Issue by trigooo** [fsantini/KoboCloud#54]
Hey, first of all, huge thanks for the project, I am using it and it works perfectly.
Is there any chance for subfolder support in the future? 
That would be very convenient because Calibre uses subfolders.

**Comment by golflabel** [comment]
> Hey, first of all, huge thanks for the project, I am using it and it works perfectly.
> Is there any chance for subfolder support in the future?
> That would be very convenient because Calibre uses subfolders.

So, do you have to leave everything at the root level of your Dropbox? I haven't installed yet, but I'm trying to figure out if it's worth it.

**Comment by trigooo** [comment]
> > Hey, first of all, huge thanks for the project, I am using it and it works perfectly.
> > Is there any chance for subfolder support in the future?
> > That would be very convenient because Calibre uses subfolders.
> 
> So, do you have to leave everything at the root level of your Dropbox? I haven't installed yet, but I'm trying to figure out if it's worth it.

that was the case when I used Dropbox, you can see in README that subfolders are not supported, BUT- pcloud subfolders do work. I changed to pcloud and it's working wonders!

**Comment by deadlyknapsack** [comment]
@VPeeters Sorry to bump this. I have Readarr set up on my NAS and that creates subdirectories by default, based on author. I then sync my .epub files with Dropbox and have this amazing tool sync my Kobo. Works amazing, but the subdirectories are preventing me from closing the whole circle. Trying to figure out how to upload my sorted epubs to a single folder in DropBox, but seems tricky. Any news on the subdirectory support for DropBox?

**Comment by VPeeters** [comment]
@deadlyknapsack I don't use Dropbox myself, but when I have time I will look into this
