### ISSUE TITLE
/usr/local/kobocloud/curl: Permission denied

### ISSUE THREAD

**Issue by paperfairy** [fsantini/KoboCloud#55]
Followed directions to the letter, attached are my log and config files, it appears my device doesn't allow for curl to be used?

My device is

> Kobo Libra H20
> Model N873
> Software Version: 4.25.15875 (7615d0aa08, 11/9/20)

[get.log](https://github.com/fsantini/KoboCloud/files/5859507/get.log)

[kobocloudrc.txt](https://github.com/fsantini/KoboCloud/files/5859508/kobocloudrc.txt)

Let me know how else I can be useful.

**Comment by tarpdalton** [comment]
Probably need to run ’chmod -R 777’ before running makeroot

**Comment by brunovg** [comment]
Hello,
I have the same problem:
`/usr/local/kobocloud/curl: Permission denied`

**Comment by brunovg** [comment]
> 
> 
> Probably need to run `chmod -R 777 ./ ` before running makeroot

-rw-r--r-- 1 0100973 1049089  223687 Nov 10 14:57 ca-bundle.crt
-rwxr-xr-x 1 0100973 1049089     194 Nov 10 14:57 config.sh*
-rwxr-xr-x 1 0100973 1049089     242 Nov 10 14:57 config_kobo.sh*
-rwxr-xr-x 1 0100973 1049089     164 Nov 10 14:57 config_pc.sh*
-rw-r--r-- 1 0100973 1049089 1930852 Nov 10 14:57 curl
-rwxr-xr-x 1 0100973 1049089    1541 Nov 10 14:57 get.sh*
-rwxr-xr-x 1 0100973 1049089    1005 Nov 10 14:57 getDropboxFiles.sh*
-rwxr-xr-x 1 0100973 1049089    1071 Nov 10 14:57 getGDriveFiles.sh*
-rwxr-xr-x 1 0100973 1049089     754 Nov 10 14:57 getOwncloudFiles.sh*
-rwxr-xr-x 1 0100973 1049089     424 Nov 10 14:57 getOwncloudList.sh*
-rwxr-xr-x 1 0100973 1049089     995 Nov 10 14:57 getRemoteFile.sh*
-rwxr-xr-x 1 0100973 1049089    1091 Nov 10 14:57 getpCloudFiles.sh*
-rw-r--r-- 1 0100973 1049089     176 Feb  2 14:22 kobocloudrc.tmpl
-rwxr-xr-x 1 0100973 1049089     687 Nov 10 14:57 udev_mount.sh*
-rwxr-xr-x 1 0100973 1049089     377 Nov 10 14:57 udev_program.sh*
-rwxr-xr-x 1 0100973 1049089     106 Nov 10 14:57 uninstall.sh*

**Comment by paperfairy** [comment]
For the less technically minded playing along at home:

https://github.com/fsantini/KoboCloud/blob/master/README.md

Skip the "Compiling" step.
For the "Installing" step, use `KoboRoot.tgz` from here: https://github.com/fsantini/KoboCloud/releases
Proceed as normal.
