### ISSUE TITLE
Wifi doesn't work after install on Clara

### ISSUE THREAD

**Issue by adacameron** [fsantini/KoboCloud#56]
Hi, I've used this script for ages without any issues, when it suddenly stopped working. I noticed that there was an update when I came back here, so I deleted and went through the whole process again, but the dropbox still didn't work, and the folder was missing in the directory - more importantly, the Wifi on my Clara doesn't work anymore - it just scans for networks, but never finds any. 

I've tried restoring to factory setting, manual resets, firmware updates, syncing over the desktop (which is the only way to get it to work at all after the factory reset), and contacting Rakuten was no help at all. It's very possible that I did something wrong when I was trying to install it, but I was hoping you might have an idea of how to solve the issue with Wifi, or at least what might've gone wrong? No worries if not, but thought it was worth a shot. 

Thank you!

**Comment by sebDK** [comment]
I got also the same issue. No WIFI network available. But, kind of weird, my clara get pick up files on Google Drive.

**Comment by sebDK** [comment]
I used the following worardound;
getting the lastest firmware from https://kbdownload1-a.akamaihd.net/firmwares/kobo3/Nov2020/kobo-update-4.25.15875.zip
adding both folders etc/udev/rules.d and usr/local/kobocloud into KoboRoot.tgz from kobo-update-4.25.15875.zip.
It was working after.

**Comment by courtoiss** [comment]
Hello sebDK and everyone,
I read with interest your comments. I'm new with kobocloud, and unfortunately i'm trying it while a problem is blocking the use of if and breaking the wifi of my ClaraHD.
I have prepared my KoboRoot.tgz as explained in the installation manual, and i have now my wifi out of order.
I have downloaded the latest firmware as you adviced it. I have put into the /etc and the /usr files of KoboCloud. 
Can you explain me two or three things ?
 - how can i correct the script getRemote.sh -> what is the problem with -o option ?
 - can you confirm me that i have to put the directory "update" and the file "KoboRoot.tgz" at the top of the directory visible when i plug Clara in my computer ?
 - when i restart the machine, nothing is done. How can i force it to update ? 
 - where can i see the log file ? I have seen it in the script "getRemote.sh" it is in /tmp/ , but i don't see this directory
 - if i manage to do the upgrade, will the Clara reset as new (will i lose my position of reading in all the books?)
Have a good week, and thank you for your answers
Sylvain

**Comment by catmcdermott** [comment]
> First the script getRemoteFile.sh need to be corrected. Curl is not running correctly (problem with -o)
> 
> I used the following worardound to keep the WIFI working;
> getting the lastest firmware from https://kbdownload1-a.akamaihd.net/firmwares/kobo3/Nov2020/kobo-update-4.25.15875.zip
> adding both folders etc/udev/rules.d and usr/local/kobocloud into KoboRoot.tgz from kobo-update-4.25.15875.zip.
> It was working after.

Amazing you found a way to fix it- I've d/ed the firmware, but could you explain in more detail exactly what to do to get the wifi working? thank you!

**Comment by sebDK** [comment]
Download the last FW version from https://kbdownload1-a.akamaihd.net/firmwares/kobo7/Nov2020/kobo-update-4.25.15875.zip.

There is a newer version but not tested

Follow procedure explained in: https://github.com/fsantini/KoboCloud
Once project source is available on your machine, replace the 2 files with:

https://github.com/sebDK/KoboCloud/blob/master/src/usr/local/kobocloud/getGDriveFiles.sh
https://github.com/sebDK/KoboCloud/blob/master/src/usr/local/kobocloud/getRemoteFile.sh

Add content of  kobocloud/etc and kobocloud/usr into kobo-update-4.25.15875.zip (there is already a etc and usr directory)
Save the zip file.
Put the zip file into your .kobo folder on your Kobo Clara HD.
Restart the ebook reader.

You can now setup .add/kobocloud/kobocloudrc with your own settings
