### ISSUE TITLE
Doesn't work on Libra's latest version

### ISSUE THREAD

**Issue by monkeyibrowstudios** [fsantini/KoboCloud#57]
After installing this on my Libra with the latest firmware, configured the dropbox and gdrive links (made sure that was a line below in the file) and nothing happened on restart. .log file first showed curl permission denied and on all the following restarts just an error that there was no wifi connection

**Comment by enragedgamer** [comment]
I'm having the same issue on my Libra. Looks like the latest firmware broke it.

**Comment by ke** [comment]
I fixed this issue by adding 'chmod 755 $KC_HOME/curl' to https://github.com/fsantini/KoboCloud/blob/master/src/usr/local/kobocloud/config.sh#L11

**Comment by ke** [comment]
I fixed this issue by adding `chmod 755 $KC_HOME/curl` to https://github.com/fsantini/KoboCloud/blob/master/src/usr/local/kobocloud/config.sh#L11

**Comment by ValuedConcepts** [comment]
Unfortunately here it also not working on my new Kobo Libra H20.

Thought it would have Dropbox Sync by default, but that is not the case. Too bad this project is needed, should be default functionality. Think I will return it and get a Pocketbook instead.

**Comment by groentebroer** [comment]
It works for me on 4.26.16704. (With NextCloud, but that should show at least some extra logs...)

Could you run the local test somewhere with your Google/Dropbox URL?
See: local_test.sh in the source.

Have you installed the release package or build it yourself. The execute permission bit might miss if installed yourself?
See: #31 as well.

**Comment by VPeeters** [comment]
@ValuedConcepts my Libra H2O works just fine. Could you provide some more details and a copy of your log file please?

**Comment by seiyaLim** [comment]
Hi, i just recently get my Libra H20 and the cloud just wouldn't sync. 
Can anyone help?
![image](https://user-images.githubusercontent.com/84626855/119227054-b42ac380-bb3e-11eb-9c87-72fb5987cf5b.png)

**Comment by VPeeters** [comment]
Try to use the pre-compiled version from KoboCloud you can download from GitHub.
