### ISSUE TITLE
Kobo Nia issues

### ISSUE THREAD

**Issue by veggysaurus** [fsantini/KoboCloud#58]
installed this on a Nia I recently purchased.
Device rebooted, could see the .add folder but syncing doesn't nothing.
also there is no kobocloudrc.tmpl, just a unix executable, log file and a library folder.. nothing else.

how to I even go about uninstalling this now, or working out why dropbox doesn't work?

**Comment by groentebroer** [comment]
@veggysaurus what does the logfile say?
Please post the output.

Maybe try a comment after the URL (or an empty line), for the URL to be picked up?
(Do you see/added your url to: `.add/kobocloud/kobocloudrc` ?
