### ISSUE TITLE
Waiting for internet connection error

### ISSUE THREAD

**Issue by cbderksen** [fsantini/KoboCloud#59]
I've been using KoboCloud successfully on my new Clara HD with GoogleDrive for about a month or so, but it has stopped working. My kobocloudrc file has only one line - the URL of my public GoogleDrive folder. After trying to sync the Kobo, the log says:

2021-03-17_10:56:41 waiting for internet connection
2021-03-17_10:56:50 done

I am able to navigate to the GoogleDrive folder in the beta browser, so I know I can connect to the internet, but for some reason, the Kobo isn't connecting to the GoogleDrive or not downloading any files. Does anyone have some suggestions on how to troubleshoot this? 

Btw, I'm a noob and have no programming experience. I was very excited that I got KoboCloud working, but I don't have enough knowledge to fix it when it breaks. Please be kind when providing advice, thanks.

**Comment by groentebroer** [comment]
Hi @cbderksen ,

Maybe try a comment after the URL (or an empty line), for the URL to be picked up?

**Comment by cbderksen** [comment]
> Maybe try a comment after the URL (or an empty line), for the URL to be picked up?

That worked!! Thanks for your help @groentebroer :)
