### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by mic85rm** [fsantini/KoboCloud#6]
this is my log file

2018-12-21_16:14:03 waiting for internet connection
Reading # Add your URLs to this file
Comment found

Reading https://www.dropbox.com/sh/"hiddenbyme"/"hiddenbyme"?dl=0
Getting https://www.dropbox.com/sh/"hiddenbyme"/"hiddenbyme"?dl=0
Getting https://www.dropbox.com/sh/"hiddenbyme"/"hiddenbyme"?dl=0
/usr/local/kobocloud/getDropboxFiles.sh: line 27: /usr/local/kobocloud/curl: Permission denied <!-- ho dato un occhiata ai sorgenti non trovo nulla riguardo a questo errore
2018-12-21_16:14:09 bind mounting to SD     <!-- risolto copiando la cartella anche su sd esterna
mount: mounting /mnt/onboard/.kobo/kobocloud/Library on /mnt/sd/kobocloud failed: No such file or directory
2018-12-21_16:14:09 done

i have kobo aura h2o  system software : 4.12.12111 del 11/12/18

thanks a lot

**Comment by fsantini** [comment]
Strange, I'm also testing on an aura h2o and it's working flawlessly. Have you tried reinstalling?

**Comment by mic85rm** [comment]
any idea?

**Comment by mic85rm** [comment]
resolve myself after kobostuff installation

**Comment by czebrahat** [comment]
Hi, could you say a bit more about how you solved this? At first I had the same issue as you (link was there, files not syncing), then I reinstalled the new tgz directory with uninstall support and now my Dropbox link isn’t recognised at all. Would love to get this working properly

**Comment by mic85rm** [comment]
hi,i think you make a factory reset and reinstall only new version of kobocloud. then if you have problem you try install kobostuff. meanwhile post here text inside your kobocloudrc .

**Comment by czebrahat** [comment]
thanks - I did the factory reset, but same issue. kobocloudrc is the same
as before. sorry if this is a stupid question! but what's kobostuff?

2018-12-24_14:45:12 waiting for internet connection
Reading # Add your URLs to this file
Comment found
Reading # Remove the # from the following line to uninstall KoboCloud
Comment found
Reading #UNINSTALL
Comment found
Reading
Getting


2018-12-24_14:45:22 done

**Comment by mic85rm** [comment]
kobocloudrc is different from logfile. recheck plese.
then there isn t stupid question every question is important.

kobostuff is a suite of tools for kobo like telnet  see the root of kobo etc...

but i think your problem is in kobocloudrc...

**Comment by czebrahat** [comment]
oh yeah, I meant the get file is the same.

kobocloudrc looks like this

# Add your URLs to this file
# Remove the # from the following line to uninstall KoboCloud
#UNINSTALL

https://www.dropbox.com/sh/lbez377sr9hyx5b/AADXvaxHcmbHtdqupIjQP4F_a?dl=0

**Comment by mic85rm** [comment]
ok try to put in your dropbox folder a simple txt file with shortname and retry...i try your folder in my kobo and don't see your epub file.

**Comment by czebrahat** [comment]
ok I've put a txt file in the folder. the log now just says

2018-12-24_17:11:53 waiting for internet connection

**Comment by mic85rm** [comment]
ok try kobostuff...http://mr-public.auth-2ac4bfee353948ec8ea7fd1710574097.storage.sbg1.cloud.ovh.net/Kobo/kobo-stuff-1.5.N-r15570.tar.xz

**Comment by czebrahat** [comment]
Still nothing... idk if I'm doing something wrong or maybe just not
compatible with clara hd. thanks though.
