### ISSUE TITLE
/usr/local/kobocloud/curl: Permission denied

### ISSUE THREAD

**Issue by taylanumert** [fsantini/KoboCloud#60]
2021-03-22_21:19:58 waiting for internet connection
Reading # Add your URLs to this file
Comment found
Reading # Remove the # from the following line to uninstall KoboCloud
Comment found
Reading #UNINSTALL
Comment found
Reading https://drive.google.com/drive/folders/xxxxxxxxxxxxxxxxxxxxxxxxxx?usp=sharing
Getting https://drive.google.com/drive/folders/xxxxxxxxxxxxxxxxxxxxxxxxxx?usp=sharing
Getting https://drive.google.com/drive/folders/xxxxxxxxxxxxxxxxxxxxxxxxxx?usp=sharing
xxxxxxxxxxxxxxxxxxxxxxxxxx
/usr/local/kobocloud/getGDriveFiles.sh: line 16: /usr/local/kobocloud/curl: Permission denied
2021-03-22_21:20:02 done

**Comment by groentebroer** [comment]
Hi @taylanumert

Could you run the local test somewhere with your Google URL?
See: local_test.sh in the source.

Have you installed the release package or build it yourself. The execute permission bit might miss if installed yourself?
See: https://github.com/fsantini/KoboCloud/issues/31 as well.
