### ISSUE TITLE
Not registering any valid URL on kobocloudrc

### ISSUE THREAD

**Issue by jam-cv** [fsantini/KoboCloud#61]
After adding the .tgz file to the .kobo dir, and restarting- nothing happens, it doesnt recognize my Google drive folder or anything. 
kobocloudrc is up to date, matching the tmpl file in the original source. 
No indication on kobo libra that any file on the (shared) GD directory is available at all. 
is there anything that needs to happen in the kobo filesystem itself besides a restart?
it's also unclear why you indicate the .exec file needs to be modified after installation... the file matches the config tmpl file, why would it need to be changed? 
Can't tell if i'm missing something, but its frustrating. 
Appreciate your help, thank you so much

**Comment by groentebroer** [comment]
Hi @jam-cv ,

No log file as well in the resulting folder?
Maybe try a comment after the URL (or an empty line), for the URL to be picked up?
