### ISSUE TITLE
[Kobo Forma] get.log write no connection detected

### ISSUE THREAD

**Issue by ebauger** [fsantini/KoboCloud#65]
Hi @fsantini

This project sound promising!

I actually have a Kobo Forma with the lastest firmware 4.26.16704

I install the prebuilt package and follow the configuration files and reboot many times for Google Drive url

First try

**get.log**
```
❯ cat get.log                                                                                                                           kobocloud
2021-04-20_17:16:58 waiting for internet connection
2021-04-20_17:26:02 error! no connection detected
```

second try on get.log
```
^B^@^@^@^A�^K^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```

I can help for debugging your project and try to create a fix on get.sh with my kobo.

**Comment by groentebroer** [comment]
Hi @ebauger I have a Libra H2O with 4.26.16704 as well.
Could you run the local test somewhere with your Google URL?
See: `local_test.sh` in the source.

**Comment by ebauger** [comment]
certainly, I will get back to you in a few days ✌️

**Comment by groentebroer** [comment]
Sure! But to claify this will be testing from your local (linux) machine... (Or shell).
