### ISSUE TITLE
Access denied on my Libra H20

### ISSUE THREAD

**Issue by seiyaLim** [fsantini/KoboCloud#79]
Hi, 
i just recently get my Libra H20 and the cloud just wouldn't sync.
Can anyone help?
![119227054-b42ac380-bb3e-11eb-9c87-72fb5987cf5b](https://user-images.githubusercontent.com/84626855/119227174-3f0bbe00-bb3f-11eb-9fb5-793655eefdda.png)

**Comment by VPeeters** [comment]
See #9
