### ISSUE TITLE
casually files dont show from dropbox problem

### ISSUE THREAD

**Issue by mic85rm** [fsantini/KoboCloud#8]
getfile after mod at usr/local/kobocloud of my kobo h2o

2018-12-23_23:40:39 waiting for internet connection
Sto leggendo # Add your URLs to this file
Commento trovato
Sto leggendo # Remove the # from the following line to uninstall KoboCloud
Commento trovato
Sto leggendo #UNINSTALL
Commento trovato
Sto leggendo 
Getting 

Sto leggendo https://www.dropbox.com/sh/?dl=0
Getting https://www.dropbox.com/sh/?dl=0
Getting https://www.dropbox.com/sh/?dl=0
linkLine=https://www.dropbox.com/sh/?dl=0
linkLine=

 -> /mnt/onboard/.kobo/kobocloud/Library/
Remote size: 
sh: -ge: argument expected

curl: Can't open '/mnt/onboard/.kobo/kobocloud/Library/'!
curl: try 'curl --help' or 'curl --manual' for more information
Error resuming: redownload file
getRemoteFile ended
linkLine=

 -> /mnt/onboard/.kobo/kobocloud/Library/
Remote size: 
sh: -ge: argument expected
curl: Can't open '/mnt/onboard/.kobo/kobocloud/Library/'!
curl: try 'curl --help' or 'curl --manual' for mo

**Comment by bogorad** [comment]
Same problem here, with Google Drive. Used to work fine, but suddenly stopped. Kobo H2O.

`2021-07-31_22:12:13 waiting for internet connection
Reading # Google Drive
Comment found
Reading https://drive.google.com/drive/folders/*****?usp=sharing
Getting https://drive.google.com/drive/folders/*****?usp=sharing
Getting https://drive.google.com/drive/folders/*****?usp=sharing

File info: 
File code: 
File name: 
Download: /usr/local/kobocloud/curl --cacert "/usr/local/kobocloud/ca-bundle.crt" -k --silent -C - -L --create-dirs -o /mnt/onboard/.add/kobocloud/Library/ https://drive.google.com/uc?id=&export=download -v
Status: 23
Output: 
curl: Can't open '/mnt/onboard/.add/kobocloud/Library/'!
curl: try 'curl --help' or 'curl --manual' for more information
Remote file information:
  Status code: 
getRemoteFile ended
2021-07-31_22:12:20 done
`
