### ISSUE TITLE
Is it possible to add Seafile as a cloud provider?

### ISSUE THREAD

**Issue by korry73** [fsantini/KoboCloud#80]
Is it possible to add Seafile (www.seafile.com) as a cloud provider?

**Comment by korry73** [comment]
Thanks, I can try, but my dev skills are close to zero. I expect my Kobo on Monday and I will test.

**Comment by groentebroer** [comment]
@korry73 It would help if you could supply a (permanent at best) shared folder with one file in it: ulysses.epub (download it for example from here: https://nc01.adruna.org/s/Y72RfYJM79jct8N ). That would help create a test setup for yourself and others for KoboCloud....

**Comment by korry73** [comment]
@groentebroer , @VPeeters , thanks!

I have a self-holsted Seafile server and can provide any support required. I have uploaded ulysses,epub here: https://seacloud.no-ip.info/d/c1b9d3d19b9b40959cc6/ Please let me know is anything else is needed. You can also register an account on my server. Seafile supports webdav if it is needed for books sync.

**Comment by VPeeters** [comment]
If it supports webdav it should be relatively easy to implement this... I will see what I can do.

**Comment by korry73** [comment]
Yep, it does, this is the webdav url on my server: https://seacloud.no-ip.info/seafdav/ You can register an account to test. Let me know if sth is needed (logs etc.)

**Comment by VPeeters** [comment]
I will look into it this Saturday.

**Comment by vietchovui** [comment]
yeah. I hope that mega.nz cloud service could be added. This free service gives 50gig storage and it's very fast.
