### ISSUE TITLE
files not syncing to Libra H2O with no log errors

### ISSUE THREAD

**Issue by junefish** [fsantini/KoboCloud#81]
I just setup Dropbox sync.  `/.add/kobocloud/Library` is empty.  `../../get.log` has:
```
2021-06-02_21:15:30 waiting for internet connection
Reading # Add your URLs to this file
Comment found
Reading # Remove the # from the following line to uninstall KoboCloud
Comment found
Reading #UNINSTALL
Comment found
2021-06-02_21:15:36 done
```
My kobocloudrc config file has (with full dropbox URL partially redacted):
```
# Add your URLs to this file
https://www.dropbox.com/sh/SHARELINK?dl=0
# Remove the # from the following line to uninstall KoboCloud
#UNINSTALL
```

I put a PDF and an EPUB in the dropbox folder but after syncing over wifi on my Kobo I still don't see the files.

**Comment by VPeeters** [comment]
This is strange... Did you reboot your Kobo after changing the config file? It seems like it doesn't even read the link.

**Comment by junefish** [comment]
I had rebooted twice (once after installing the .tgz, once after changing the config file) and it hadn't worked…but I just rebooted again now and both the PDF and EPUB synced immediately.  Guess it needed 1 more reboot (as all technology seems to).
