### ISSUE TITLE
GDrive stopped working (was: Can't open '/mnt/onboard/.add/kobocloud/Library/')!

### ISSUE THREAD

**Issue by MasikEzisen** [fsantini/KoboCloud#83]
Hi,

I found this in the log file today:
curl: Can't open '/mnt/onboard/.add/kobocloud/Library/'!
curl: try 'curl --help' or 'curl --manual' for more information (log attached)

When I tried to rollback to the previous release it just didn't see the link in the kobocloudrc file.

I also tried factory reset and then reinstalling the feature but the result is the same.

Can you please check it out or give me a way to solve this issue?

Thank you.

[get.log](https://github.com/fsantini/KoboCloud/files/6819179/get.log)

**Comment by gi-mo** [comment]
Hi,
same issue here. Suddenly I can't sync no more my Clara HD with my Drive Account.
Same log than MasikEzisen.
Please let me know how to fix it. Thanks a lot!

**Comment by Blueder** [comment]
Same for me, please help if anyone knows a fix

**Comment by Blueder** [comment]
I tried using my PCloud drive instead of Google Drive and it worked.
I also added a line break at the end of the link, not sure if it matters though.

**Comment by gi-mo** [comment]
> I tried using my PCloud drive instead of Google Drive and it worked.
> I also added a line break at the end of the link, not sure if it matters though.

Please explain. What do you mean for "line break"? thanks dude...

**Comment by Blueder** [comment]
press enter after the end of your link

> > I tried using my PCloud drive instead of Google Drive and it worked.
> > I also added a line break at the end of the link, not sure if it matters though.
> 
> Please explain. What do you mean for "line break"? thanks dude...

**Comment by gi-mo** [comment]
Ok, it doesn't work for me. Thanks.

Il gio 15 lug 2021, 14:37 Blueder ***@***.***> ha scritto:

**Comment by Blueder** [comment]
did you try using pcloud instead of google drive?
I also did use a prebuilt package in the release section of this github instead of building it from source. People also mention that could be a solution.

**Comment by gi-mo** [comment]
> did you try using pcloud instead of google drive?
> I also did use a prebuilt package in the release section of this github instead of building it from source. People also mention that could be a solution.

Thank you so much Blueder, you're so kind. I need to sync Kobo with Drive.
And yes, I used a prebuilt package.
I'm afraid it's something related to wifi because wifi icon has a very strange behavior now: flash to 5 bars when I power up the Kobo, then goes to 1 or 2 bars and disconnect after 30/60" randomly. But I can use Chrome and charge web pages... It's a mystery for me. I'll just wait for a fix. Have a great day!

**Comment by MohnJadden** [comment]
I'm running into this issue as well.  My wifi is having no problems - I can get to the Kobo Store and buy books without issues.  I updated to the latest version of Kobocloud via the prebuilt package installer and the issue persists.  

`2021-07-15_20:58:15 waiting for internet connection
Reading # Add your URLs to this file
Comment found
Reading https://drive.google.com/drive/folders/redacted?usp=sharing
Getting Reading https://drive.google.com/drive/folders/redacted?usp=sharing
Getting Reading https://drive.google.com/drive/folders/redacted?usp=sharing
Redacted
File info: 
File code: 
File name: 
Download: /usr/local/kobocloud/curl --cacert "/usr/local/kobocloud/ca-bundle.crt" -k --silent -C - -L --create-dirs -o /mnt/onboard/.add/kobocloud/Library/ https://drive.google.com/uc?id=&export=download -v
Status: 23
Output: 
curl: Can't open '/mnt/onboard/.add/kobocloud/Library/'!
curl: try 'curl --help' or 'curl --manual' for more information
Remote file information:
  Status code: 
getRemoteFile ended
Reading # Remove the # from the following line to uninstall KoboCloud
Comment found
Reading #UNINSTALL
Comment found
2021-07-15_20:58:26 done
`

**Comment by fsantini** [comment]
Dear all, I just had a quick check. It's not a local Kobo problem, something changed in the Google Drive web interface and it needs to be adapted. I'll have a look as soon as possible.

**Comment by gi-mo** [comment]
Thank you so much! 😉

Il ven 16 lug 2021, 09:15 fsantini ***@***.***> ha scritto:

**Comment by VPeeters** [comment]
I have time to look into this tomorrow. :-)

**Comment by MohnJadden** [comment]
Just wanted to say thanks to the folks running and collabing - Kobocloud is a kickass application and the fact that it's being done for free is nuts.  Thank you for your time and effort!

**Comment by VPeeters** [comment]
Should be fixed in the latest version. Can somebody confirm?

**Comment by gi-mo** [comment]
Sorry for a really dumb question: I need to uninstall and install again?
Can I just update, maybe? 😅

Il ven 23 lug 2021, 19:18 VPeeters ***@***.***> ha scritto:

**Comment by VPeeters** [comment]
No you can just install it again. There should be no need to uninstall it first. However, please make sure to reboot your device

**Comment by gi-mo** [comment]
> No you can just install it again. There should be no need to uninstall it first. However, please make sure to reboot your device.
> 
> So: just download & install it again as if it is a new installation.

It works with some issues:
- no more graphic on Kobo about charging books as before
- wifi signal is very weak (even in contact with the usual router with a HUGE signal in my flat)
- wifi disconnects by himself after 1' or less and I have to reconnect manually
- just one book synced over 3 new I put in my usual Drive bin
Thanks for your efforts but I'm still in troubles.

**Comment by VPeeters** [comment]
Did you reboot your device? It is highly unlikely that those issues are related to this issue.

**Comment by gi-mo** [comment]
> Did you reboot your device? It is highly unlikely that those issues are related to this issue.

Yes I did, several times. And I tried another wifi too. I had these same issues same day I was no more able to sync Drive. For weeks before it was perfect: great wifi signal, fast sync.

**Comment by VPeeters** [comment]
Please send your logs.

**Comment by gi-mo** [comment]
[get.log](https://github.com/fsantini/KoboCloud/files/6870428/get.log)

**Comment by VPeeters** [comment]
I tested your drive folder, seems to work fine here. However, I see in your logs something is going wrong. I am trying to figure out how this is possible... How did you install KoboCloud on your device?

**Comment by gi-mo** [comment]
> I tested your drive folder, seems to work fine here. However, I see in your logs something is going wrong. I am trying to figure out how this is possible... How did you install KoboCloud on your device?

Following instruction here.

Download the latest KoboRoot.tgz from the Release page (or using this direct link).
Copy it into the Kobo device:
Connect the Kobo device and mount it (you should be able to access to the kobo filesystem)
Copy the .tgz archive in the .kobo directory(1) of your device
Unplug and restart your Kobo device

Thanks a lot

**Comment by VPeeters** [comment]
I cannot replicate this issue. Your books download just fine when I'm testing. It might be related to your connection problems. Could you see if the connection issue persists after uninstalling KoboCloud?

**Comment by gi-mo** [comment]
Ok,

**Comment by gi-mo** [comment]
It seems better. More strength on the signal (4 instead of 1) but slower on recognizing wifi. And I need to write down a password  EVERY time I use a wifi, even if it is labeled as SAVED. I'm trying with two different wifi.

**Comment by gi-mo** [comment]
Maybe I break my Clara HD using KoboCloud for a couple of weeks?

**Comment by VPeeters** [comment]
Now re-install KoboCloud, and see what happens. I doubt KoboCloud is the issue here, and if it is, it is a separate issue. Please open a new issue as I'm closing this one because the original issue is solved.

**Comment by MohnJadden** [comment]
Confirming the latest version works on a Libra H2O, TYVM!
