### ISSUE TITLE
EPUB does not appear in "My Books" after first attempt at Cloud Mod  

### ISSUE THREAD

**Issue by Creative348** [fsantini/KoboCloud#87]
I followed the steps carefully from the code webpage.    
I used this guide https://findingbytes.com/2020/06/07/kobo-cloud
Watched the video many times before attempting.  
I contacted the software developer, no reply yet.  

I checked .kobo folder after copying TGZ file.  
It's not there, settings are set to show hidden files.

Could there be software in Windows 10, in the latest readers that deletes the TGZ file? 
Are further modifications required? Change advanced settings in one or both of the drives in the reader? 

Is that the reason why Lewis Carroll's famous book from Guttenberg in my Google Drive doesn't appear in Kobo Libra? 
Has anyone also encountered this problem after attempting Cloud Mod in the latest readers?

Thanks, 
S

**Comment by VPeeters** [comment]
Did you reboot your kobo after putting the tgz there? Does it disappear? Do you use de pre-built version?

**Comment by Creative348** [comment]
I used the one click install, Koboreader and Plato.  

I did reboot.  

I found that every time I put the tgz in the .kobo directory.  
It disappeared.  

Does Windows think it's malware? 
I retried 5 times.  

tgz disappears everytime.

**Comment by VPeeters** [comment]
That is possible. But not very likely. When does the file disappear?

**Comment by cferron** [comment]
On my Mac I see the file disappearing also. The sync seems to work however... I had issue today after my Kobo upgraded so I recopied the .tgz as instructed, rebooted and it synched my Epub files that I was trying to sync... Not sure what happened.

Kobo clara HD
4.28.18220 (23b2a16e39, 21-08-07)

**Comment by Creative348** [comment]
@VPeeters  The file disappears just after I move it into .kobo directory.

**Comment by Creative348** [comment]
@cferron I wasn't able to sync with Calibre no matter what settings I chose in Koboreader.  
I looked thoroughly at what options there are and looked online and found solutions.  
None of them worked and the day after I installed Koboreader it started to crash.  

https://user-images.githubusercontent.com/88633535/129423296-25fc6d06-2ea2-47ea-ad5a-f2f53a77900e.mp4

**Comment by Creative348** [comment]
Each time I repeat the steps you listed.  
.tgz file disappears from .kobo 
I don't know if defender treats as malware 
somehow .tgz file doesn't remain in .kobo
