### ISSUE TITLE
Google Drive  curl: Can't open '/mnt/onboard/.add/kobocloud/Library/'!

### ISSUE THREAD

**Issue by puffnut** [fsantini/KoboCloud#88]
I had Kobocloud working perfectly with Google Drive.  Then all of a sudden it stopped working, newly added books won't sync with my Kobo.  I factory reset the Kobo and reinstalled kobocloud, but the problem still persists.  Here is my Get file log (i have removed part of the link text for privacy). Something about not being able to access Kobocloud library?

2021-08-16_21:51:06 waiting for internet connection
Reading https://drive.google.com/drive/folders/1SuChgcuz5O7H20MycjcbaHip?usp=sharing
Getting https://drive.google.com/drive/folders/1SuChgcuz5O7H20MycjcbaHip?usp=sharing
Getting https://drive.google.com/drive/folders/1SuChgcuz5O7H20MycjcbaHip?usp=sharing
1SuChgcuz5O7H20MycjcbaHip
File info: 
File code: 
File name: 
Download: /usr/local/kobocloud/curl --cacert "/usr/local/kobocloud/ca-bundle.crt" -k --silent -C - -L --create-dirs -o /mnt/onboard/.add/kobocloud/Library/ https://drive.google.com/uc?id=&export=download -v
Status: 23
Output: 
curl: Can't open '/mnt/onboard/.add/kobocloud/Library/'!
curl: try 'curl --help' or 'curl --manual' for more information
Remote file information:
  Status code: 
getRemoteFile ended
2021-08-16_21:51:16 done

Is anyone able to help with this problem?  Thank you

**Comment by VPeeters** [comment]
Are you sure the GDrive link is still publicly accessible?

**Comment by puffnut** [comment]
Yes, it says anyone with this link can view.

**Comment by VPeeters** [comment]
There seems to be something wrong with the mount. Which e-reader do you have? Did you use the pre-built version from this repo?

**Comment by puffnut** [comment]
I'm using the Kobo Libra H20, and yes I followed the instructions and got the file from this repo.  I can follow the folder path to where library is on the .add folder, so it does exist, but this doesn't seem to be able to find it.  Thanks for the help so far btw.

**Comment by VPeeters** [comment]
Is the Library folder writeable? I don't understand. I have a H2O but can't reproduce the issue... Do you have the same issue using the test link?

**Comment by puffnut** [comment]
Okay, the library folder was ticked as read only, like in the photo below, so I unticked it.  However when I plug it back in, it appears ticked again and it hasn't solved the issue.   I tried with the test link and that also hasn't solved the issue.

Only thing I did notice was that when I plug the H20 into my PC, after restarting it, it comes up saying 'There's a problem with this drive, scan now to fix it' could that be related?  Maybe I should do another factory reset and try again.

**Comment by VPeeters** [comment]
That could definitely be related. Worst case scenario the SD card in your e-reader might be failing. Repairing or reformatting the memory card might solve the issue

**Comment by puffnut** [comment]
I did another factory reset, and started again from scratch.  And it works!  I don't think I did anything differently, so perhaps the factory reset reformatted, and fixed the drive. 

Thank you very much for your help, hopefully it doesn't happen again!
