### ISSUE TITLE
curl: Can't open '/mnt/onboard/.add/kobocloud/Library/'!

### ISSUE THREAD

**Issue by Apophis52** [fsantini/KoboCloud#89]
Booted e-reader with the .tgz and everything was working fine, added a pdf to the google drive and got this eror.
[get.log](https://github.com/fsantini/KoboCloud/files/7016871/get.log)

**Comment by VPeeters** [comment]
See #88

**Comment by mswitakowski** [comment]
It could be related to https://github.com/fsantini/KoboCloud/issues/111
