### ISSUE TITLE
Request update for Libra 2

### ISSUE THREAD

**Issue by northman11** [fsantini/KoboCloud#95]
I followed the instructions to install KoboCloud to allow my Libra 2 to access a shared Google Drive folder. Unfortunately, it doesn't work. I checked everything again but I don't see where I made a mistake. I'm curious if anyone else got this to work on the new Libra 2.

**Comment by pavelgutin** [comment]
I was able to get it working. A mistake I made the first time around was extracting the TAR file from the TGZ and copying that over.

**Comment by jucor** [comment]
Works on my Libra2 for a Dropbox folder. The mistake I made was to forget to add a newline at the end of the koborc line with my Dropbox link.
