### ISSUE TITLE
Books are not deleted

### ISSUE THREAD

**Issue by dgsiegel** [fsantini/KoboCloud#96]
Looking at the project description I was expecting that downloaded books which get deleted on the server will not be downloaded again. However as KoboCloud just gets a list of the current files on the server (only looked at Nextcloud) and downloads them all via curl, books will never be deleted.

To support this, I'd imagine we'd need to keep track on the downloaded books in a file (similar to get.log) and then delete them, if they're no longer on the remote.

**Comment by VPeeters** [comment]
Yes but this would fundamentally change how KoboCloud works. Don't know if it's something users want

**Comment by louisabraham** [comment]
I think it's now implemented with the REMOVE_DELETED option!
