### ISSUE TITLE
Support for kepubify

### ISSUE THREAD

**Issue by dgsiegel** [fsantini/KoboCloud#97]
I run almost all my epubs through https://github.com/pgaskin/kepubify, as it gives me a few features I like (zooming on images, correct page numbering, annotations over multiple pages etc.). As it also has some releases for ARM, it might be possible to run it directly on the Kobo. For example, we could add a setting to kobocloudrc (or a new file) to force conversion of all epubs to kepubs automatically when downloading. Would that be something you'd be interested?

**Comment by fsantini** [comment]
I use kepubify too :) If it's an optional setting, why not. I just wouldn't want it on my old Kobo because I know it would just take too long.

**Comment by tylpk1216** [comment]
> I run almost all my epubs through https://github.com/pgaskin/kepubify, as it gives me a few features I like (zooming on images, correct page numbering, annotations over multiple pages etc.). As it also has some releases for ARM, it might be possible to run it directly on the Kobo. For example, we could add a setting to kobocloudrc (or a new file) to force conversion of all epubs to kepubs automatically when downloading. Would that be something you'd be interested?

I wrote an app to send file to Kobo device by Web-UI, it converts EPUB to KEPUB by kepubify core library. I use Golang to implement my project so it is easily to do this converting. My device is Elipsa, the converted time is 1 ~ 5 seconds for small files.

https://github.com/tylpk1216/kobofileserver

**Comment by folkemat** [comment]
> https://github.com/tylpk1216/kobofileserver

Oh that's very cool! With this, you no longer have to start a server on Android! I've always wondered why no one has developed something like this. The QR code saves you the annoying typing. Very nice, I will try it later. You should introduce it on Mobileread.com
