### ISSUE TITLE
Limit syncs to a configurable interval

### ISSUE THREAD

**Issue by michaelarnauts** [fsantini/KoboCloud#98]
Right now, every time WiFi is turned on, the sync will start. This causes the Kobo to sync every time something is looked up online (online search, actual sync, ...). I think it would make sense to only sync once a day, or (if possible), tied into the actual syncing to the Kobo service itself.

Also, right now (with the nextcloud integration, but I assume it happens with every integration) it tries to download every file (curl does something to check if the filesize had changed) and this can take quite a while. Maybe it shouldn't try to download files that are already on the device? You can always delete them and they will be redownload anyway.

**Comment by groentebroer** [comment]
You dan influence the sync with enabling/disabling the WiFi. Just put out WiFi, will save your battery as well (even without KoboCloud).
